### ISSUE TITLE
[2-WAY COMMUNICATION]: Time series chart

### ISSUE THREAD

**Issue by pratibhapandey16** [opensearch-project/observability#1007]
2 way communication for Time series chart as per #987 

@abasatwar @spattnaik

**Comment by ruchika-narang** [comment]
Hi @mengweieric 

I have raised a PR for 2 way sync for timeseries as per current implementation. The current implementation doesn't let the user select any other value in dimension except for a timestamp type value. As we have 2 way sync implementation done, there is a date histogram field which gets the timestamp so the dimension button is disabled.
As per the implementation of timeseries chart in plotly(https://plotly.com/javascript/time-series/) it only takes date value on x-axis. 
Please let me know, how do you want us to implement multi dimensions in timeseries visualization with 2 way sync?

Thanks,
Ruchika
