### ISSUE TITLE
[2-WAY COMMUNICATION]: Log view chart 

### ISSUE THREAD

**Issue by pratibhapandey16** [opensearch-project/observability#1015]
2 way communication for Log view as per https://github.com/opensearch-project/observability/pull/987

@abasatwar @spattnaik

**Comment by elfisher** [comment]
Does it make sense to combine this with https://github.com/opensearch-project/observability/issues/1014 given that both are linked to the same PR?

**Comment by mengweieric** [comment]
Not in scope any more.
