### ISSUE TITLE
[BUG] Save visualization broken in App Analytics

### ISSUE THREAD

**Issue by eugenesk24** [opensearch-project/observability#1097]
**What is the bug?**
When you create a visualization in Application Analytics events tab, and then save it. 
The visualization comes up as No Results in the panel tab.
<img width="1682" alt="Screen Shot 2022-10-10 at 3 28 00 PM" src="https://user-images.githubusercontent.com/92330893/194940723-93133ce9-2f57-45e9-808e-7d30a5174eca.png">

**How can one reproduce the bug?**
1. Go to Application Analytics
2. Create an application with "source = opensearch_dashboards_sample_flights" as log source
3. Go to Events tab
4. Add "where DestCityName = "Venice" | stats count() by span( timestamp , 6h )" to query
5. Go to Visualization and save visualization
6. Go to Panels tab
7. See No Results

**What is the expected behavior?**

**What is your host/environment?**
 - OS: iOS
 - Version 2.3
 - Plugins Observability

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by ruchika-narang** [comment]
Hi @mengweieric , this issue will be fixed once this PR https://github.com/opensearch-project/observability/pull/1116 will be merged in. We tested this one on our local and it seems to work!
