### ISSUE TITLE
[BUG]: Update chart in Log Events tab of Application Analytics does not update the query properly and does not show correct chart 

### ISSUE THREAD

**Issue by DipraAich** [opensearch-project/observability#1136]
**What is the bug?**
Update chart in Log Events tab of Application Analytics does not update the query properly and does not show correct chart 

**How can one reproduce the bug?**
1: Create a new application in application analytics.
2: Fill the form with application name and source of the logs and create a new application.
3. Add configuration and click on Update chart.

Uploading Untitled (3).mp4…

**What is the expected behavior?**
The proper query should get populated into the PPL query panel and corresponding chart should be represented.

**Comment by DipraAich** [comment]
Hi @mengweieric, @eugenesk24,

We found an observation. We have attached a video replicating our observation. Kindly let us know if this behaviour is expected.

https://user-images.githubusercontent.com/61182817/196752712-5c36b738-74a9-4dca-848a-6521cc5d0254.mp4

cc: @ruchika-narang

**Comment by eugenesk24** [comment]
> Hi @mengweieric, @eugenesk24,
> 
> We found an observation. We have attached a video replicating our observation. Kindly let us know if this behaviour is expected.
> 
>  Untitled.4.mp4 
> cc: @ruchika-narang

This is expected. Availability can only be set on visualizations that are an aggregation over time. I am working on drafting a document that captures all of Application Analytics' expected behavior.
