### ISSUE TITLE
[Bug bash 2.4] Chart selection and tabs in the side panel should not scroll, they should anchor on fix position (on top)

### ISSUE THREAD

**Issue by btzeng** [opensearch-project/observability#1137]
![Image](https://user-images.githubusercontent.com/93013804/195895159-6b56617f-e5f0-4762-a9c9-ee3c01b0f4de.png)

**Comment by ruchika-narang** [comment]
Hey @btzeng , we have logged this bug already and started working on it. The number is #1123 . It'd be great if you can close this one. Thanks!

**Comment by mengweieric** [comment]
Closed as it was fixed.
