### ISSUE TITLE
[BUG]: Query fails when it includes the field 'ip' in it.

### ISSUE THREAD

**Issue by ruchika-narang** [opensearch-project/observability#1148]
**What is the bug?**
The query fails with the screenshot as attached when we have 'ip' field in dimensions. 
Query: source = opensearch_dashboards_sample_data_logs | stats avg(bytes), max(bytes) by span(timestamp,1d),  host, ip

**What is the expected behavior?**
The query should not fail and display visualization as expected.

**Do you have any screenshots?**
![MicrosoftTeams-image (21)](https://user-images.githubusercontent.com/79983862/196234673-c5371310-36a1-47af-81ff-1211291ed883.png)

**Comment by mengweieric** [comment]
ip is the reserved keyword, therefore you need to wrap it with the backtick
