### ISSUE TITLE
[BUG]: Timestamp is getting displayed in heatmap from other configurations.

### ISSUE THREAD

**Issue by harshada8989** [opensearch-project/observability#1175]
**What is the bug?**
The timestamp is getting displayed in the heatmap from other configurations. Where in the case of heatmap user selects the configurations.

**How can one reproduce the bug?**
1. Go to any visualization
2. Save timestamp as a first dimension
3. Go to the heatmap
4. Timestamp is pre-selected whereas in heatmap user selects manually all configuration.

**Comment by mengweieric** [comment]
Currently it's expected behavior.
