### ISSUE TITLE
[FEATURE] Persist redux data on browser

### ISSUE THREAD

**Issue by mengweieric** [opensearch-project/observability#1177]
**Is your feature request related to a problem?**
Currently, redux state data gets lost on page refresh, which leads to bad user experience.

**What solution would you like?**
Propose to use redux persist 6.0 which provides out of box solution for redux toolkit and just need some additional but straitforward configurations. 

**What alternatives have you considered?**
As far as I know there aren't too many options out there for redux toolkit specifically, there is one middleware called redux-storage where its last activity happened roughly 6 years ago. Feel free to left comments if there are other better options available.

**Do you have any additional context?**
The downside of redux persist 6.0 is: when last time there were updates is 12 months ago, and the last released version is roughly 3 years ago as 6.0.0. But currently it works fine in our cases with current functionalities it supports.

**Comment by derek-ho** [comment]
@mengweieric closing this since the PR was merged
