### ISSUE TITLE
[BUG] Interval for histogram in event analytics is inconsistent

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/observability#1249]
**What is the bug?**
Clicking in the patterns table seems to reset the selected interval, but the selected interval in the dropdown is not changed - this should be consistent, either reset to default and have dropdown change with it or keep the same interval and update the chart accordingly

**How can one reproduce the bug?**
1. Go to event analytics and run a query
2. histogram interval says `minute` but is actually `year`
3. change `minute` to `hour`
4. change `hour` back to `minute`
5. the histogram interval is now `minute`
6. update state (update the query, or click a pattern in the patterns table to add a filter)
7. the histogram interval is back to `year`

**What is the expected behavior?**
The interval should persist

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by joshuali925** [comment]
I updated the issue title and added reproduction steps, this is not specifically to patterns but more of an issue in event explorer

**Comment by derek-ho** [comment]
Thanks! Will try to work on a fix next week to get more familiar with the code base

**Comment by derek-ho** [comment]
Fixed with PR: #1266
