### ISSUE TITLE
[BUG] :  Breakdown values is getting merged into the Dimension section.

### ISSUE THREAD

**Issue by harshada8989** [opensearch-project/observability#1276]
**What is the bug?**
When a user clicks on the update chart breakdown values get merged into the dimension array.

**How can one reproduce the bug?**
1. Go to any visualization and enter query
2. Click on refresh button
4. Scroll down to Configuration Panel
5. Click on click to add button in the breakdown section
6. Add any Breakdown from the dropdown
7. Click back and Click on the Update Chart button
8. See Breakdown values get merged into the dimension section.

**What is the expected behavior?**
Breakdown values should not get merged into the Dimension section.

**Comment by harshada8989** [comment]
@mengweieric @anirudha 
cc: @ruchika-narang @spattnaik

**Comment by ruchika-narang** [comment]
hi @mengweieric , @anirudha 

Attached is the video for the bug.
[bug video.webm](https://user-images.githubusercontent.com/79983862/201940682-52d0a7be-4d5e-49d6-b319-af4e78e32e8f.webm)

Thanks!!

**Comment by mengweieric** [comment]
thanks for reporting this, but this is the expected behavior for now.
