### ISSUE TITLE
[BUG] Selecting an Override Pattern on SideBar of Event Analytics Explorer

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/observability#1296]
**What is the bug?**
Selecting an Override Pattern on SideBar of Event Analytics Explorer changes nothing in the patterns table and causes infinite loading of the sidebar.

**How can one reproduce the bug?**
Go to Playground Event Analytics
Use query `source = opensearch_dashboards_sample_data_logs `
Override the default pattern by selecting a pattern field on the sidebar
Nothing changes, and sidebar pattern fields start infinitely loading

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by joshuali925** [comment]
> should the expected behavior here be to update the pattern table with the selected pattern and update the query in the search bar to add `| ${selectedPattern}`? Or just update the pattern table and don't touch the query in the search bar?

we decided to not change user query explicitly when using patterns UI. This two way sync needs query parsing. same as https://github.com/opensearch-project/observability/issues/1300
