### ISSUE TITLE
Add auto github release workflow

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/observability#1406]
### Is your feature request related to a problem?
As part of OpenSearch releases, `opensearch-build` pushes a tag for the release commit.
But publishing a github release based on the tag is manual.

### What solution would you like?
We've added this workflow[1] in OpenSearch which publishes github releases automatically when a tag is pushed.

Add this workflow to all repos releasing software in the project.
See example: https://github.com/opensearch-project/OpenSearch/blob/main/.github/workflows/auto-release.yml
Example Release: https://github.com/opensearch-project/OpenSearch/releases/tag/2.5.0

[1] https://github.com/opensearch-project/opensearch-plugins/blob/main/WORKFLOWS.md#auto-github-releases

**Comment by ps48** [comment]
The feature is added in https://github.com/opensearch-project/observability/pull/1436

**Comment by saratvemulapalli** [comment]
Looks like the workflow is failing: The notes are not in the right format. 
https://github.com/opensearch-project/observability/actions/runs/4318116929/jobs/7536017277
```
Run ncipollo/release-action@v1
Error: Error undefined: ENOENT: no such file or directory, open 'release-notes/opensearch-observability.release-notes-test-release-automation.md'
```

**Comment by joshuali925** [comment]
i think it's expected, the failed action was triggered by tag `test-release-automation`, which is not a release tag. there's no clear pattern (e.g. `v*` like in ODFE) to match a release tag so currently all tags would trigger the workflow

cc: @Swiddis
