### ISSUE TITLE
[FEATURE] Community driven Integration repository

### ISSUE THREAD

**Issue by YANG-DB** [opensearch-project/observability#1457]
**Is your feature request related to a problem?**
We would like to create a "Community driven" Integration repository hub for sharing, uploading, commenting and collaboration 
Individual contributors or companies would be able to create / update / share / download their integrations without any need to wait for confirmation from the Opensearch dev team.

**What solution would you like?**
- create a "Community driven" Integration repository hub 
- create mechanisms for loading / sharing / security-verification / collaboration of integrations
- create review and ranking capabilities 
- be able to categorize according to maturity / downloads / popularity
- allow loading from this Integration hub

**What alternatives have you considered?**
Use github

**Do you have any additional context?**
- https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3412

**Comment by derek-ho** [comment]
Wrong Repo, but initial issue still stands/is pending
