### ISSUE TITLE
[Discussion] Final API list and interface for integrations

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/observability#1462]
List API - this can be combined with filter in that generic list will just be without any filters
- GET _integration/repository?filter=type:Logs&category:web,html
- Should only return barebones of what UI needs to show panel (image url, description)

Inspect specific integration API
- GET _integration/repository/$name
- Should return everything about this integration, namely more details description, license, SSO fields, etc.
- In my opinion, these info should not be returned on List since it is not necessary, but open to suggestions here

Add integration API
- PUT _integration/store/$instance_name/activate
- Options can be added like they want to add viz, but not query by just add query parameters to this API

Get integration status API
- GET _integration/store//status?filter=blah
- Will return success or UX message to show if failed as a list for added integrations

**Comment by YANG-DB** [comment]
hi
