### ISSUE TITLE
[FEATURE] Integration Validation Endpoint

### ISSUE THREAD

**Issue by Swiddis** [opensearch-project/observability#1466]
**Is your feature request related to a problem?**
Per work on integrations, an endpoint needs to be added that can validate an integration. The validation logic was implemented in #1464, so this issue mostly concerns routing.

The endpoint consumes a zip file containing the integrations.

**What solution would you like?**
The design of the API as a whole is described in #1446, the main action item for this ticket is implementing the `/store/{id}/validate` endpoint.

**What alternatives have you considered?**
Validation could be done as a part of the storage process instead of as its own endpoint. This logic should be included, but having a separate endpoint also enables more-expensive full validation of a completed integration, instead of validating individual components.

**Do you have any additional context?**
[Integration Project](https://github.com/orgs/opensearch-project/projects/106)
[#1443](https://github.com/opensearch-project/observability/issues/1443)

**Comment by Swiddis** [comment]
Further work requires progress on #1456 to get a consistent idea on how integrations will be processed by the API. Paused to prioritize that.

**Comment by derek-ho** [comment]
Outdated
