### ISSUE TITLE
Add support for sample data & sample datasets from OpenSearch

### ISSUE THREAD

**Issue by YANG-DB** [opensearch-project/observability#1471]
Add test data in the sample folder that can be loaded as part of the loading capabilities

**Comment by YANG-DB** [comment]
# Highlights 
Once a user loads an integration, he will have the ability to load pre-generated sample data onto the designated index/data-stream and open the loaded assets for inspection and exploration .

## Usage
In a similar approach that was taken in the [playground](https://observability.playground.opensearch.org/app/home#/tutorial_directory) we would like to allow an integration to have the capability of loading sample data and enabling the user to play with the loaded assets and investigate its capabilities.

![add sample data](https://user-images.githubusercontent.com/48943349/225425706-400d2b1e-cb80-4dd9-baae-62658b5f4d3b.png)

## User Flow

**Assumptions**
Integration template contains sample data
 - Sample data is tagged with an appropriate `sample` indication under the `attributes` object
```
 {
  "@timestamp": "2023-02-24T17:18:11.000Z",
  "body": "29.51.229.106 - - [24/Feb/2023:17:18:11 +0000] \"POST /gumboots HTTP/1.1\" 404 34152 \"-\" \"Go-http-client/1.1\"",
  "trace_id": "102981ABCD2901",
  "http": {
    "response": {
      "status_code": "404",
      "bytes": 34152
    },
    "url": "/gumboots",
    "flavor": "1.1",
    "request": {
      "method": "POST"
    }
  },
  "span_id": "abcdef1010",
  "event": {
    "result": "success",
    "domain": "nginx.access",
    "type": [
      "access"
    ],
    "category": [
      "web"
    ],
    "name": "access",
    "kind": "event"
  },
  "attributes": {
    "sample":"true",
    "data_stream": {
      "type": "logs",
      "namespace": "production",
      "dataset": "nginx.access"
    }
  },
  "communication": {
    "source": {
      "address": "127.0.0.1",
      "ip": "29.51.229.106"
    }
  },
  "observerTime": "2023-02-24T17:18:11.000Z"
}

```
User has selected an integration template for loading and has successfully loaded the integration into the store.

The user now has selected to load sample data - this selection will trigger the next phases :

 - verify existence of the Integration's index pattern for example for the next index pattern `ssfo_logs-production-us_east` 
 - bulk load the sample data into this designated index by calling the next API
     -  `PUT _integration/store/{name}/load-sample-data`

User will also be able to delete the sample data by calling the next API
     -  `DELETE _integration/store/{name}/load-sample-data`

**Comment by derek-ho** [comment]
Outdated, and done
