### ISSUE TITLE
[FEATURE]Sec-Review new Rest API

### ISSUE THREAD

**Issue by YANG-DB** [opensearch-project/observability#1484]
**Is your feature request related to a problem?**
Sec-Review new REST API for Integration is needed

**What solution would you like?**
A security review is needed to verify certain aspects of the new suggested REST API

**What alternatives have you considered?**

**Do you have any additional context?**
- see https://github.com/opensearch-project/observability/blob/2.x/docs/API/swagger.yaml

**Comment by derek-ho** [comment]
https://talos.security.aws.a2z.com/#/talos

**Comment by derek-ho** [comment]
Moved to front end
