### ISSUE TITLE
[FEATURE]Add activity log to the CLI activation

### ISSUE THREAD

**Issue by YANG-DB** [opensearch-project/observability#1499]
**Is your feature request related to a problem?**

During the Integration CLI user interaction, the CLI should output a log which details all its command and responses.
This is essentially for users to be able to track what has been happening behind the scenes and if something fails they will be able to submit an activity log with the failing issue.

**What solution would you like?**
Add a logging mechanism that will log all the activities (including responses) and allow it be submitted as an issue so that it would include version and other relevant details for issue tracing.

**What alternatives have you considered?**

**Do you have any additional context?**
[Integration CLI RFC](https://github.com/opensearch-project/observability/issues/1451)

**Comment by derek-ho** [comment]
Outdated Repo @Swiddis please re-open/recreate once/if this gets prioritized with new details based on the design of the project in the hopefully new repo, thanks
