### ISSUE TITLE
[FEATURE]Support OTEL demo for OpenSearch 

### ISSUE THREAD

**Issue by YANG-DB** [opensearch-project/observability#1508]
**Is your feature request related to a problem?**
Support [OTEL Demo](https://github.com/open-telemetry/opentelemetry-demo) with OpenSearch Observability as the ingestion store.

**What solution would you like?**
Fork [OTEL Demo](https://github.com/open-telemetry/opentelemetry-demo)  and use OpenSearch Observability plugin including simple schema as the backing signal store

 - Allow adding opentelemetry-demo to OpenSearch project
 - Enable attachments of Observability Log resource onto this demo (nginx for example)
 - Enable relevant dashboards and monitoring / alerts assets relevant to this topology (using the integration framework)
 - Add this demo to the Observability playground 

**What alternatives have you considered?**

**Do you have any additional context?**
- [OTEL Demo](https://github.com/open-telemetry/opentelemetry-demo) 
- [Nginx Integration](https://github.com/opensearch-project/observability/tree/main/integrations/nginx)
- [Service Map Integration](https://github.com/opensearch-project/observability/tree/main/integrations/service-map)
- [Observability Simple Schema](https://github.com/opensearch-project/observability/blob/main/docs/schema/observability/README.md)

### Tasks
- remove grafana
- update docker-compose services to incude O/S + dashboard
- support O/S K8s - research if to use helm chart or operator
- O/S data-stream 
    - add relevant logs components to mapping template
    - predefine data-stream from all signals (traces, services, metrics, logs)
    - add Prometheus datasource
- Create additional Logs components to match missing parts
- support dedicated services fields - https://opentelemetry.io/docs/demo/manual-span-attributes/

**Comment by YANG-DB** [comment]
WIP - https://github.com/YANG-DB/opentelemetry-demo/tree/opensearch-observability-otel

**Comment by derek-ho** [comment]
@YANG-DB closing this as done
