### ISSUE TITLE
Compatibility with segment replication

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/observability#1562]
### Summary
With 2.9.0 release, there are lot of enhancements going in for segment replication[1][2] feature (went GA in 2.7.0), we need to ensure different plugins are compatible with current state of this feature. Previously, we ran [tests](https://github.com/opensearch-project/OpenSearch/issues/6602) on plugin repos to verify this compatibility but want plugin owners to be aware of these changes so that required updates (if any) can be made. With `2.10.0` release, [remote store feature](https://github.com/opensearch-project/OpenSearch/issues/2992) is going GA which internally uses SEGMENT replication strategy only i.e. it enforces all indices to use `SEGMENT` replication strategy. So, it is important to validate plugins are compatible with segment replication feature. 

#### 1. Refresh policy behavior
1. RefreshPolicy.IMMEDIATE will only refresh primary shards but not replica shards immediately. Instead post refresh, primary will start  a round of segment replication to update the replica shard copies leading to eventual consistency.
2. RefreshPolicy.WAIT_UNTIL ensures the indexing operation is searchable in your cluster i.e. RAW (Read after write guarantee). With segment replication, this guarantee is not promised due to delay in replica shared updates from asynchronous background refreshes.

####  2. Refresh lag on replicas
With segment replication, there is inherent delay in documents to be searchable on replica shard copies. This is due to the fact that replica shard copies over data (segment) files from primary. Thus, compared to document replication, there will be on average increase in amount of time the replica shards are consistent with primaries.

#### 3. System/hidden indices support
With https://github.com/opensearch-project/OpenSearch/pull/8200, system and hidden indices are now supported with `SEGMENT` replication strategy. We need to ensure there are no bottlenecks which prevents system/hidden indices with segment replication.

### Next steps
With segment replication strong reads are not guaranteed. Thus, if the plugin needs strong reads guarantees specially as alternative to change in behavior of refresh policy and lag on replicas (point 1 and 2 above), we need to update search requests to target primary shard only. With https://github.com/opensearch-project/OpenSearch/pull/7375, core now supports primary shards only based search. Please follow [documentation](https://opensearch.org/docs/latest/api-reference/search/#the-preference-query-parameter) for examples and details

### Open questions
In case of any questions or issues, please post it in [core](https://github.com/opensearch-project/OpenSearch/issues/8211) issue

### Reference
[1] [Design](https://github.com/opensearch-project/OpenSearch/issues/2229)

[2] [Documentation](https://opensearch.org/docs/latest/tuning-your-cluster/availability-and-recovery/segment-replication/index/)

**Comment by dreamer-89** [comment]
Request owners to add `v2.9.0` label on this issue. @dai-chen

**Comment by dreamer-89** [comment]
Hi Plugin Owners,
Gentle reminder to look into this issue as code freeze date for `2.9.0` release is near i.e. July 11th.

**Comment by dreamer-89** [comment]
Gentle reminder for plugin owners as we are past code freeze date for 2.9.0 release

**Comment by ps48** [comment]
@dreamer-89 For Observability plugin, users create objects in the observability-dashboards plugin and may want to view immediately in the UI. Thus, we are adding the search preferences to `_primary`. Usually, there number of objects created is low in volume and small in size. We don't see heavy load on primary due to our requests.

**Comment by dreamer-89** [comment]
> @dreamer-89 For Observability plugin, users create objects in the observability-dashboards plugin and may want to view immediately in the UI. Thus, we are adding the search preferences to `_primary`. Usually, there number of objects created is low in volume and small in size. We don't see heavy load on primary due to our requests.

Thanks @ps48 for the update. `_primary` preference based search may work for search queries.

In case, your plugin performs realtime reads via [get](https://opensearch.org/docs/latest/api-reference/document-apis/get-documents/)/[mget](https://opensearch.org/docs/latest/api-reference/document-apis/multi-get/) APIs, I wanted to update that core now supports realtime reads for segment replication enabled indices with https://github.com/opensearch-project/OpenSearch/issues/8536. So, if your plugin performs search via get/mget APIs only, then there should be no change needed. Please check https://github.com/opensearch-project/OpenSearch/issues/8536 for more details.

**Comment by joshuali925** [comment]
i see in https://github.com/opensearch-project/sql/pull/2013 you mentioned 
> Existing OpenSearchDataSourceMetadataStorage.java uses match_all & term based search queries which does not provide strong reads and thus as part of https://github.com/opensearch-project/sql/issues/1801 there was no need to perform _primary based routing

In observability, there are get and search APIs, the search API also uses term based search queries https://github.com/opensearch-project/observability/blob/4345041ed16ba89082c481c9e8e326ffa1f73739/src/main/kotlin/org/opensearch/observability/index/ObservabilityIndex.kt#L277, i believe the same statement applies here. closing

**Comment by joshuali925** [comment]
@dreamer-89 thanks for the note, we do prefer strong reads if possible for better user experience. 

I see targeting `_primary` was recommended in the original issue, WAIT_FOR is [used by dashboards](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/d7004dc5b0392477fdd54ac66b29d231975a173b/src/core/server/saved_objects/service/lib/repository.ts#L127), and IMMEDIATE is recommended here. The observability and reporting plugin only stores metadata created by the user, which should imply low overhead. would you provide some guidance regarding IMMEDIATE, WAIT_FOR, and primary shard only search? i understand the distinction but i'm not sure what's recommended for our use case

**Comment by dreamer-89** [comment]
Thanks @joshuali925 for the update. 

> we do prefer strong reads if possible for better user experience.

I suggest you to confirm whether your use case needs strong reads or not. This is important before we perform any action to support strong reads. One way to achieve this is via manual testing and see if you see any discrepancy. 

> The observability and reporting plugin only stores metadata created by the user, which should imply low overhead. would you provide some guidance regarding IMMEDIATE, WAIT_FOR, and primary shard only search? i understand the distinction but i'm not sure what's recommended for our use case

As with SEGMENT replication, IMMEDIATE, WAIT_FOR refresh policies do not guarantee replica shard refreshes (and thus strong reads). The only options to get strong reads is via get/mget APIs or using _primary preference on search queries. The later puts extra burden on primary shards as all queries lands on it. But, I suggest you to first identify if strong reads are really needed or not for your use case.

CC @mch2 @anasalkouz

**Comment by joshuali925** [comment]
Not sure if i understood properly, the two statements seems a bit contradicting. Could you elaborate it a bit? e.g. if _primary is the only way for strong reads, why was IMMEDIATE brought up?

> it is still possible to have strong reads with queries you mentioned above by using [IMMEDIATE](https://github.com/opensearch-project/OpenSearch/blob/f4106a474c8503187b1d6bbe47a85a82f5243163/server/src/main/java/org/opensearch/action/support/WriteRequest.java#L92) refresh policy during indexing operations

> The only options to get strong reads is via get/mget APIs or using _primary preference on search queries

---

The reason I think we need strong read is because users will want to see the objects they created immediately after creation. For example observability allows users to add sample notebooks, it will be confusing if they clicked "Add sample notebooks" and the new sample ones doesn't show up in the notebooks list, which theoretically could happen.

Our use case is very similar to dashboards saved objects, would be better if we can align to their behavior. @kavilla do you know how is OSD saved objects handling strong reads?

**Comment by kavilla** [comment]
To avoid choosing, have we considered making it configurable? Like `_msearch` and `_search` is configurable right now.

**Comment by dreamer-89** [comment]
Thanks @joshuali925 for the comment and seeking clarification. 

There are two mechanism by which you can get strong reads as mentioned below.
1) During indexing operation. This is done by refreshing all shard copies inside the indexing operation. This results in any subsequent data search query to return the latest data. This is done today via IMMEDIATE, WAIT_FOR refresh policies. Segment replication does not support this as mentioned in issue description. 
2) During data search request. get/mget APIs and using `_primary` preference parameter ensures strong reads. This is handled automatically on core and thus with SEGMENT replication only mechanism to get strong reads.

@kavilla : I do not have much background on dashboards. Does your last comment suggest that there is no change needed ?

**Comment by joshuali925** [comment]
Thanks. I think we would want to align with OSD behavior, since observability objects should act in the same way as OSD saved objects

**Comment by joshuali925** [comment]
i did some manual testing in observability, didn't see inconsistent behavior. will close the issue for now
