### ISSUE TITLE
[BUG] Flaky IT test

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/observability#1597]
**What is the bug?**
Possibly related to Seg Rep changes

**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by joshuali925** [comment]
i think the discussion is still ongoing https://github.com/opensearch-project/observability/issues/1562

we will probably align to osd behavior

**Comment by joshuali925** [comment]
there were multiple CI runs in https://github.com/opensearch-project/observability/pull/1778

but they were consistently failing or succeeding, no flaky runs. closing for now
