### ISSUE TITLE
Fix repository URL in nginx integration 

### ISSUE THREAD

**Issue by mmehrten** [opensearch-project/observability#1749]
Current URL is incorrect and references "integrarions": 
https://github.com/opensearch-project/observability/blob/c23e6f29afef8eab1a02702dc3a2133dacac1b32/integrations/nginx/config.json#L42C9-L42C9

**Comment by derek-ho** [comment]
Hello @mmehrten, integrations has been moved to a different repo, code is mainly in https://github.com/opensearch-project/dashboards-observability, and documentation is split there and https://github.com/opensearch-project/opensearch-catalog. Will be closing this for now. Thanks for pointing it out though. CC @YANG-DB
