### ISSUE TITLE
[Live Tail] Supporting live tail on the observability plugin

### ISSUE THREAD

**Issue by anirudha** [opensearch-project/observability#23]
* Migrate `logviewer-kibana-plugin` repo from ODFE to OpenSearch
* Rule on whether LiveTail should be added to Observability

**Comment by louzadod** [comment]
Hi, @anirudha. Do you have an idea about when in the roadmap this feature fit?
Thanks in advance.

**Comment by davidcui1225** [comment]
Hi @louzadod , the Live Tail feature is currently roadmapped to be released in OpenSearch 1.3.
