### ISSUE TITLE
Generate and upload code coverage report through CI workflow

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/observability#252]
**Is your feature request related to a problem? Please describe.**
Code coverage information for all the OpenSearch plugins should be shown in the Codecov dashboard (https://app.codecov.io/gh/opensearch-project/).
Related issue: https://github.com/opensearch-project/opensearch-plugins/issues/73

**Describe the solution you'd like**
Please update the CI workflow to generate code coverage and upload it to Codecov.

**Describe alternatives you've considered**
n/a

**Additional context**
The guide for reporting the code coverage for OpenSearch plugins is located here. (https://github.com/opensearch-project/opensearch-plugins/blob/main/TESTING.md#code-coverage-reporting)

**Comment by ps48** [comment]
Added the Code Coverage and other code data as part of https://github.com/opensearch-project/trace-analytics/pull/298
