### ISSUE TITLE
Event analytics ignores timezone

### ISSUE THREAD

**Issue by tgueldner** [opensearch-project/observability#348]
**Description**
There is a difference between the time selection of Event analytics and the one used in the discover feature. Opensearch Discover converts timestamps to local user timezone. I guess it's discovered by browser settings? Using the same log data under Event analytics shifts the timestamp by an hour - in my example situated in UTC+1.

**Reproduce**
1. Collect log data from a server like access logs, something just-in-time, logged in UTC
2. Open Discover and select the index pattern for this index
3. Use a browser which doesn't use UTC.
4. Check your time selector on the right: use last 15 minutes as default
5. You should see some log entries (depends on your source of course)
6. Switch to Observability -> Event Analytics
7. Input a PPL for the same index (example: `source = logs-myserver`)
8. Check your time selector on the right again: use last 15 minutes as default
9. no data 

**Expected behavior**
I would expect to see the same log entries under Event Analytics which are shown under Discover.

**Plugins**
Default plugins of OpenSearch 1.2.1

**Host/Environment (please complete the following information):**
 - Docker Env
 - Opensearch 1.2.1

**Comment by mengweieric** [comment]
Hi @tgueldner ,

This issue has been fixed in 1.3 release. Feel free to reopen it if you still see this issue in 1.3.
