### ISSUE TITLE
Overlay service performance data on graph

### ISSUE THREAD

**Issue by prashanttct07** [opensearch-project/observability#440]
**Is your feature request related to a problem? Please describe.**
Current trace analytics feature does not have an option to display the performance metrics such as txn/min, avg latency etc for each component, we need to go to explicit component to triage the issue. 

**Describe the solution you'd like**
Would like to see performance metrics for each component while analyzing the traces for services. 

**Describe alternatives you've considered**
AWS Xray has the feature and would like to get it built on OpenSearch trace analytics as well.

**Comment by joshuali925** [comment]
on service map node: show transaction per minute - throughput per minute over selected time range
