### ISSUE TITLE
Visualize service map for individual trace/transaction

### ISSUE THREAD

**Issue by prashanttct07** [opensearch-project/observability#442]
**Is your feature request related to a problem? Please describe.**
Current trace analytics does not have an option to drill down the graph for component/service, for example clicking on a node in trace analytics graph should open another graph for the specific service. 

**Describe the solution you'd like**
Trace map for individual service should be shown while user click on any service in the graph 

**Describe alternatives you've considered**
AWS Xray has the feature and would like to get it built on OpenSearch trace analytics as well.

**Comment by joshuali925** [comment]
TODO filtering by service name should include other services that are used by spans of selected service

**Comment by joshuali925** [comment]
it will work like this:
filtering by service will work the same was as in service details view (non-matched service nodes will be transparent)
I'll sent a PR for this to get in 1.3 release. Also feel free to update this issue if you are expecting something different, thanks
![image](https://user-images.githubusercontent.com/28062824/156268331-d0d3c33e-ddbb-47f0-9892-efab132d0090.png)
