### ISSUE TITLE
correlation of logs and traces 

### ISSUE THREAD

**Issue by prashanttct07** [opensearch-project/observability#443]
**Is your feature request related to a problem? Please describe.**
Current trace analytics does not have an option to view the correlated logs for specific traces

**Describe the solution you'd like**
Would like to have a solution where we can easily navigate to the logs for specific traces in order to triage the issues. 

**Describe alternatives you've considered**
Need to manually go to discover and search for the logs and make the correlation

**Comment by joshuali925** [comment]
closing since #493 is merged
