### ISSUE TITLE
[BUG] Event Analytics doesn't work out of box with otel-v1-apm-span-* indexes

### ISSUE THREAD

**Issue by enp** [opensearch-project/observability#479]
Tried to use Event Analytics with existing otel-v1-apm-span-* indexes (Trace Analytics works good enough), but receiving ```Index does not contain a valid time field``` for any PPL request (```source = otel-v1-apm-span-000001 | fields kind | stats count()``` for example).

Maybe Event Analytics must knows about valid time field in otel-v1-apm-span-* indexes as Trace Analytics does?

Maybe any workaround exists to set valid time field?

**Comment by enp** [comment]
Looks like I can't use PPL in Query Workbench to request something from otel-v1-apm-span-* indexes, example from https://opensearch.org/docs/latest/observability-plugin/ppl/index works good even for simple request ```search source = accounts``` but for request ```search source = otel-v1-apm-span-000001``` I see error ```Events: Service Unavailable, this query is not runnable.```

Similar problem with SQL in Query Workbench, error is ```Otel-v1-apm-span-000001: [IllegalStateException] There was internal problem at backend, this query is not runnable```

**Comment by joshuali925** [comment]
tracking issue in SQL repo https://github.com/opensearch-project/sql/issues/438, closing this
