### ISSUE TITLE
Fix resizing viz config covering chart

### ISSUE THREAD

**Issue by eugenesk24** [opensearch-project/observability#591]
Resizing the visualization config area covers the visualization until screen is refreshed.

<img width="1792" alt="Screen Shot 2022-03-31 at 4 23 31 PM" src="https://user-images.githubusercontent.com/92330893/161165391-f82e5a44-b2f4-4385-956c-87a71b62b3cc.png">

After expanding configuration area
<img width="1792" alt="Screen Shot 2022-03-31 at 4 23 40 PM" src="https://user-images.githubusercontent.com/92330893/161165395-202c411e-563d-402e-a951-810ef274c565.png">

After clicking refresh button
<img width="1792" alt="Screen Shot 2022-03-31 at 4 23 51 PM" src="https://user-images.githubusercontent.com/92330893/161165399-b0728dee-5c64-4191-9cd3-6755ee693c46.png">

**Comment by mengweieric** [comment]
#1044 PR adopting designs of wizard app addressed this.
