### ISSUE TITLE
[BUG] Event analytics does not support index names with dots

### ISSUE THREAD

**Issue by oscarkraemer** [opensearch-project/observability#612]
**Describe the bug**
When creating a new source in app/observability-dashboards#/event_analytics/explorer I will get errors if the index name contains dots ( `.` ).

**To Reproduce**
Steps to reproduce the behaviour:
1. Have an index named with a dot e.g. `my_index-version-1.0-delete-me` clone the index so that it have a name that does not contain any dots e.g. `my_index-version-1_0-delete-me`
2. In Dashboards Observability/Event analytics/Explorer if you search for `source = my_index-version-1_0-delete-me` everything works as expected but if you search for `source = my_index-version-1.0-delete-me` you will get the following error:
```{
  "error": {
    "reason": "Invalid Query",
    "details": "Failed to parse query due to offending symbol [delete-me] at: 'source=my_index-version-1.0-delete-me' <--- HERE... More details: Expecting tokens in {'D', 'TRUE', 'FALSE', 'INTERVAL', 'MICROSECOND', 'MILLISECOND', 'SECOND', 'MINUTE', 'HOUR', 'DAY', 'WEEK', 'MONTH', 'QUARTER', 'YEAR', '.', '+', '-', '(', '`', 'AVG', 'COUNT', 'MAX', 'MIN', 'SUM', 'VAR_SAMP', 'VAR_POP', 'STDDEV_SAMP', 'STDDEV_POP', 'FIRST', 'LAST', 'ABS', 'CEIL', 'CEILING', 'CONV', 'CRC32', 'E', 'EXP', 'FLOOR', 'LN', 'LOG', 'LOG10', 'LOG2', 'MOD', 'PI', 'POW', 'POWER', 'RAND', 'ROUND', 'SIGN', 'SQRT', 'TRUNCATE', 'ACOS', 'ASIN', 'ATAN', 'ATAN2', 'COS', 'COT', 'DEGREES', 'RADIANS', 'SIN', 'TAN', 'ADDDATE', 'DATE', 'DATE_ADD', 'DATE_SUB', 'DAYOFMONTH', 'DAYOFWEEK', 'DAYOFYEAR', 'DAYNAME', 'FROM_DAYS', 'MONTHNAME', 'SUBDATE', 'TIME', 'TIME_TO_SEC', 'TIMESTAMP', 'DATE_FORMAT', 'TO_DAYS', 'SUBSTR', 'SUBSTRING', 'LTRIM', 'RTRIM', 'TRIM', 'LOWER', 'UPPER', 'CONCAT', 'CONCAT_WS', 'LENGTH', 'STRCMP', 'RIGHT', 'LEFT', 'ASCII', 'LOCATE', 'REPLACE', 'LIKE', 'ISNULL', 'ISNOTNULL', 'IFNULL', 'NULLIF', 'IF', 'SPAN', 'MS', 'S', 'M', 'H', 'W', 'Q', 'Y', ID, INTEGER_LITERAL, DECIMAL_LITERAL, DQUOTA_STRING, SQUOTA_STRING, BQUOTA_STRING}",
    "type": "SyntaxCheckException"
  },
  "status": 400
}
```

**Expected behavior**
Indices with names that does contains dots ( `.` ) works in the same ways as indices without dots.

**Plugins**
OpenSearch v1.2.0

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: CentOS-7 
 - Version: OpenSearch v1.2.0 installed with tar.

**Additional context**

**Comment by penghuo** [comment]
## Why query execution failed.
Currently, [PPL support index name with DATE/VERSION format as suffix](https://github.com/opensearch-project/sql/blob/main/ppl/src/main/antlr/OpenSearchPPLLexer.g4#L289). for example, `my_index-version-1.0.0` is supported.  Because `.` usually separate catalog and index, for example, query remote cluster, `source = remoteCluster.index`. 

## Alternative Solution
You could [delimited identifiers](https://github.com/opensearch-project/sql/blob/main/docs/user/general/identifiers.rst#delimited-identifiers), for example, 
```
source = `my_index-version-1.0-delete-me`
```
