### ISSUE TITLE
Bump the version for 1.3.2 opensearch-dashboards release

### ISSUE THREAD

**Issue by abhinavGupta16** [opensearch-project/observability#631]
**Is your feature request related to a problem?**
Post Release activity https://github.com/opensearch-project/opensearch-build/issues/1885 - 

We need to bump the version for 1.3.2 in 1.x and 1.3 branches for 1.3.2 releases wrt to the release issue - https://github.com/opensearch-project/opensearch-build/issues/1882

ETA - 04/14/2022

**Comment by anirudha** [comment]
@abhinavGupta16 when is the code freeze for this ? @mengweieric

**Comment by zelinh** [comment]
We could close this issue as #695 was merged.
