### ISSUE TITLE
Time series chart support in event analytics.

### ISSUE THREAD

**Issue by amrutaBasatwar** [opensearch-project/observability#639]
1.Add time series chart as a dropdown option. Refer dropdown element on top right corner of image.
2.on selection of it, it should render a time series chart based on data selected.
3.If data does not have timestamp information , show ` no record found ` message.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/39627728/162904744-b092c7be-39b0-417b-8c48-ca24a31498e4.png)

**Comment by pratibhapandey16** [comment]
Have created the below new issue for Time series chart.
https://github.com/opensearch-project/observability/issues/673
