### ISSUE TITLE
Gauge chart support in event analytics.

### ISSUE THREAD

**Issue by pratibhapandey16** [opensearch-project/observability#640]
1. Add gauge chart as a dropdown option. Refer dropdown element on top right corner of image.
2. On selection of it, it should render a gauge chart based on data selected.
3. If data does not have timestamp information , show `<no record found>` message.

<img width="908" alt="Capture" src="https://user-images.githubusercontent.com/103417380/162942621-68883cd7-9dda-498d-9fcc-2aae47a3e497.PNG">

This issue includes the below tasks.
- [ ] Adding Gauge chart to the dropdown on the UI
- [ ] Cypress Testing(Automation)

**Comment by anirudha** [comment]
@mengweieric , we disabled it ; as it needed to be perfected before a release

**Comment by nidhisinghai** [comment]
Adding a Video For Cypress Testing for 'Gauge Chart Render'

https://user-images.githubusercontent.com/103416937/164247556-40274da8-d392-4af1-bac1-75b1bdf095ec.mp4

**Comment by abasatwar** [comment]
hi @mengweieric ,
Added video of gauge chart. Working on showing `no result found` component until user selects `series` and `value` option.

https://user-images.githubusercontent.com/78089449/164250879-d8a06614-35e8-4633-a684-a7bdca24afa7.mp4




Thanks,
Amruta

**Comment by anirudha** [comment]
thanks @amrutaBasatwar , this looks great

**Comment by abasatwar** [comment]
PR is raised for this ticket - https://github.com/opensearch-project/observability/pull/689

**Comment by ramneet-persistent** [comment]
Hi @mengweieric @anirudha 
below points are considered as per discussion
- adding dimensions and apply aggregate
- only 10 timestamp needs to be considered if no field selected in aggregate
- remove values option from UI

Thanks

**Comment by ramneet-persistent** [comment]
Hi @mengweieric @anirudha

as per issue #787 , I haven't found anything in official documentation for legend placement w.r.t gauge chart.

**Comment by ramneet-persistent** [comment]
Hi @mengweieric @anirudha
please refer attached screenshots. 

1. Single threshold: displayed using threshold object in gauge object
<img width="932" alt="single_threshold" src="https://user-images.githubusercontent.com/105915936/176457347-ad7f9bd4-ca3c-4056-8571-e3bef3875b2a.png">


2. Multiple thresholds: this is work around to display multiple markers on gauge. Please confirm if we need to continue with same. Also Do we need to add some limit on data panel to add max three thresholds. say disable "Add threshold" button after 3 limits are added in case of gauge chart
. 
<img width="936" alt="multiple_thresholds_workaround" src="https://user-images.githubusercontent.com/105915936/176457272-372bb2f2-f2e1-437f-a9c0-82238a6055ef.png">

Please share your inputs

Thanks

**Comment by ramneet-persistent** [comment]
Hi @mengweieric @anirudha
Below are few queries we have for gauge chart: 

1. Legend placement: unable to find reference for legends in documentation
2. Display gauge chart on initial load
3. Do we need to hide/disable "add threshold" button in case of multiple thresholds reached to max limit i.e. 3. 
4. Multiple thresholds: we used a workaround to display multiple thresholds. which may not be visible in some cases( depends on gauge value). Please refer comment above and [https://github.com/opensearch-project/observability/issues/640#issuecomment-1170029477]
5. as per mentioned in #787. chart with multiple dimensions and multiple metrics is done but its not readable. Kindly us know we need to add UI to limit no. of gauges displayed. Refer attached ss
<img width="931" alt="multiple_dimensions_multiple_metrics" src="https://user-images.githubusercontent.com/105915936/176886151-b9d1728b-9fde-486b-abd7-4fe0a0f7ae00.png">

above screen shot is of output of PPL query with 3 dimensions and 2 metrics. query results in arrays of length 1000 from which 10 is sliced. As 2 metrics were in query, 20 gauges displayed 
Please share your inputs

Thanks
