### ISSUE TITLE
State timeline chart support in event analytics

### ISSUE THREAD

**Issue by pratibhapandey16** [opensearch-project/observability#641]
1. Add State timeline chart as a dropdown option. Refer dropdown element on top right corner of image.
2. On selection of it, it should render a State timeline chart based on data selected.
3. If data does not have timestamp information , show `no record found` message.

<img width="908" alt="Capture" src="https://user-images.githubusercontent.com/103417380/162978368-6cc9eb93-68a8-4fdf-b0ec-ae6af3fad5cb.PNG">

This issue contains the below tasks.

- [ ] Adding State timeline chart to the dropdown on the UI
- [ ] Cypress testing(Automation)

**Comment by pratibhapandey16** [comment]
Hi @anirudha, 
Are we planning to have this chart?

CC: @mengweieric @btzeng @abasatwar @spattnaik

**Comment by mengweieric** [comment]
Resolved, line chart is renamed to timeseries.
