### ISSUE TITLE
Histogram chart support in event analytics

### ISSUE THREAD

**Issue by pratibhapandey16** [opensearch-project/observability#643]
1. Add Histogram chart as a dropdown option. Refer dropdown element on top right corner of image.
2. On selection of it, it should render a Histogram chart based on data selected.
3. If data does not have timestamp information , show `no record found` message.
<img width="908" alt="Capture" src="https://user-images.githubusercontent.com/103417380/162980075-720c3a13-2077-45f5-ba5a-e2b6bc499722.PNG">

This issue contains the below tasks.
- [ ] Adding Histogram chart to the dropdown on the UI.
- [ ] Cypress Testing(Automation)

**Comment by ruchika-narang** [comment]
Hi @mengweieric ,

The video depicts the basic implementation of the Histogram. The files were already present for histogram but required a few changes to show the data correctly. 

https://user-images.githubusercontent.com/79983862/164215843-21ac52bc-5c34-418b-ad10-04810598ab28.mp4

Have a few questions related to this graph implementation:
1. We will need an icon for histogram to be displayed in the dropdown.
2. Do we need the Value options of x-axis and y-axis both or just either of them? As what I observed in the code written already in the file and on plotly, the histogram tends to take data of only one axis. 

Thanks,
Ruchika

**Comment by pratibhapandey16** [comment]
Added Cypress automated test cases for rendering the Histogram chart and saving the visualization.

https://user-images.githubusercontent.com/103417380/164253108-fba01d79-c522-43d1-852c-13c9b227c1c8.mp4

**Comment by ruchika-narang** [comment]
Hi @mengweieric @btzeng 

I have raised a WIP PR #743  for the implementation of color theme for each category. Please can you have a look and let me know if I should proceed with this implementation for color theme.

Thanks!

**Comment by ruchika-narang** [comment]
Hey @mengweieric @btzeng @anirudha 

As we discussed about colorscale prop not working in histogram instead color works for every bar. Here is the issue link of plotly that says color works for Histogram. https://github.com/plotly/plotly.js/issues/1984
I tried using colorscale as implemented for treemap but it doesn't work. 
Let me know if I need to continue with the current implementation of color theme or you have a better idea to implement colorscale as for treemap.

Thanks!!
@abasatwar @spattnaik

**Comment by ruchika-narang** [comment]
> Hey @mengweieric @btzeng @anirudha
> 
> As we discussed about colorscale prop not working in histogram instead color works for every bar. Here is the issue link of plotly that says color works for Histogram. [plotly/plotly.js#1984](https://github.com/plotly/plotly.js/issues/1984) I tried using colorscale as implemented for treemap but it doesn't work. Let me know if I need to continue with the current implementation of color theme or you have a better idea to implement colorscale as for treemap.
> 
> Thanks!! @abasatwar @spattnaik

Please let me know the update regarding this. Should I proceed with the current implementation?

Thanks!
