### ISSUE TITLE
Tree Map chart support in event analytics 

### ISSUE THREAD

**Issue by pratibhapandey16** [opensearch-project/observability#664]
1. Add Tree Map chart as a dropdown option. Refer dropdown element on top right corner of image.
2. On selection of it, it should render a Tree Map chart based on data selected.

![image](https://user-images.githubusercontent.com/103417380/163942085-383cf18c-cf44-4bb6-990a-dede92391a80.png)

This issue contains the below tasks.

- [ ] Adding Tree Map chart to the dropdown on the UI
- [ ] Cypress testing(Automation)

**Comment by mrunal-z** [comment]
Hi @mengweieric,

The basic implementation of the Treemap chart is as shown: 

https://user-images.githubusercontent.com/79525611/164252860-60486cdd-e966-4270-915b-9eacadafc89c.mp4

**For now, we are displaying the treemap till 2 levels:**

- 1 level chart - Created by default, the label field is picked from any of the y-axis fields and the value field is any numerical field. Can also be created by leaving the parent field empty in value options.

- 2 level chart - Created by adding parent field and label field in the proper hierarchy, and value field as any numerical field.  

In cases where the tree map cannot be formed (if the value field is not numerical, or the label field and parent field are the same) then the 'No results found' placeholder is displayed.

**Inputs needed:**

- To form more nested charts, we need the option to dynamically add multiple parent fields. We will need designs for the config panel to add this feature.
- Currently, treemap chart doesn't have any icon in the Eui Icons library, so which one do we use?

Thanks,
Mrunal

**Comment by mrunal-z** [comment]
Hey @mengweieric @btzeng -
In #670, in the chart config table, there are no config options listed for treemap yet. 
Currently, I have included the following options in the config panel:
1. Panel options- title, description
2. Value mappings - parent field, child field, value field

Can you please let me know what other options we will need to add?
Thanks!
@anirudha @abasatwar @spattnaik

**Comment by mengweieric** [comment]
Hi @mrunal-z,

Thanks for the demo, it looks good. I'll work with ux for the flow to add more fields. For treemap, please go ahead to add chart styles (this is renamed from chart option) and add specific style config options like color palate to it.

Thanks

**Comment by btzeng** [comment]
@mrunal-z  Treemap config updated

**Comment by btzeng** [comment]
@ruchika-narang  Good work on parent/child inputs as well as color theme selections. Thanks for sharing the video!

**Comment by mrunal-z** [comment]
Hey @mengweieric , @btzeng 

Here is the demo video for the implementation of tiling algorithm and single color config options -

https://user-images.githubusercontent.com/79525611/169537397-abf961d7-7f74-43b9-afa0-ac16c36c254d.mp4

@btzeng , as we know, the same single color selected applies to both parent and child elements.
I have implemented 2 other options that we can consider instead:

1. We allow the user to select one color, which gets applied to the child elements, while a lighter shade of the color applies to the parent elements.


https://user-images.githubusercontent.com/79525611/169537536-a9860e0d-725d-455b-8c07-1a18b8e5c764.mp4


2. We allow the user to select colors for both parent and child fields. We can see the colorpicker for parent only after the parent field is selected. However, as per the current implementation of the config panel, we cannot detect if a parent field has been selected until we have clicked **'Preview'**. If we decide to move forward with this approach, then I can look into this further and try to show the colorpicker on selection itself.


https://user-images.githubusercontent.com/79525611/169537647-985b7330-b492-4194-9b96-f1fdc916f805.mp4


Let me know if I should go ahead with either of these.

Thanks!
@anirudha @abasatwar @spattnaik

**Comment by btzeng** [comment]
@mrunal-z  Yes, let's have both. 1. auto assign a different shade of same color to parent. 2. user assign colors to child and parent.

**Comment by mrunal-z** [comment]
Hey @btzeng  @mengweieric 

I have added both the options for color theme as shown in the following video:

https://user-images.githubusercontent.com/79525611/171186180-5216bf5d-daee-4700-801b-9f6662200e43.mp4

Let me know if this looks correct and if any other changes are required. Thanks!
