### ISSUE TITLE
[BUG] Notebooks roles missing

### ISSUE THREAD

**Issue by FalkoSp** [opensearch-project/observability#665]
**What is the bug?**
- A user wants to create a Notebook, and gets an error message "Please ask your administrator to enable Notebooks for you."
- The admin (me) tries to find out what rights or roles to give to the user, and finds nothing in the documentation.

**How can one reproduce the bug?**
1. Create a user name TestUser with roles "readall" and "opensearch_dashboards_user"
2. TestUser logs into OpenSearch Dashboards, ensures that he uses Global tenant.
3. TestUser goes to Observability/Notebooks
4. TestUser clicks on "Create Notebook", enters a name, clicks on "Create", and the error appears.
5. The error points to the complete documentation of a OpenSearch release we don't use yet (1.3).

**What is the expected behavior?**
A clear and concise description of what rights and roles I have to give to TestUser.

**What is your host/environment?**
 - AWS OpenSearch Service
 - Version 1.2
 - Default plugins

Kind greetings and thank you for help.

Edit, 2 days later: Please help! I love these notebooks, but nobody except the admin can use them, that's a pity!

**Comment by joshuali925** [comment]
Hi, does this work for you? https://github.com/opensearch-project/security/issues/1759#issuecomment-1098347740

**Comment by FalkoSp** [comment]
Many thanks!, this does it. 
Kind greetings from Hamburg, Europe.
Falko

**Comment by joshuali925** [comment]
Thanks for confirming. Looks like this got added to documentation website, linking it here if anyone else runs into the same issue https://opensearch.org/docs/latest/observability-plugin/observability-security/
