### ISSUE TITLE
Disable 'Save' functionality when user does not selects X-axis and Y-axis for graph rendering

### ISSUE THREAD

**Issue by pratibhapandey16** [opensearch-project/observability#666]
1. Add X-axis and Y-axis options for the charts using dropdown options.
2. `Unable to save visualization` toast message should be prompted if the user miss to select either X-axis or Y-axis.
![image](https://user-images.githubusercontent.com/103417380/163960201-4d888271-ee2d-48d2-8f1f-65eebb0c9b04.png)

**Comment by rinku-kumar-psl** [comment]
Hi @mengweieric ,

The video attached will describe the implementation of the below part:
 - Default axes selected on Data config value options
 - Error toast If the user selected any invalid or empty axis
 - Error toast if the user trying to save the visualization, If f user selected any invalid or empty axis
 
Please have a look, and suggest If there are any further changes needed in these scenarios

https://user-images.githubusercontent.com/103560761/165540497-27f21d62-c37c-47ca-8ef1-27ebb52c48c6.mp4

Thanks,
Rinku
