### ISSUE TITLE
Time series chart support in event analytics.

### ISSUE THREAD

**Issue by pratibhapandey16** [opensearch-project/observability#673]
1. Add time series chart as a dropdown option. Refer dropdown element on top right corner of image.
2. On selection of it, it should render a time series chart based on data selected.
3. If data does not have timestamp information , show `no record found` message.

![Capture2](https://user-images.githubusercontent.com/103417380/164236331-e4774009-c6e3-4357-bbb2-fabca69a61c9.JPG)

This issue includes the below tasks.
- [ ] Adding Time series chart to the dropdown on the UI
- [ ] Cypress Testing(Automation)

**Comment by rinku-kumar-psl** [comment]
Hi @mengweieric ,

The below-attached video depicts the basic Time-series chart implementation. 
We have taken reference for its implementation from  [Plotly](https://plotly.com/javascript/time-series/)

Chart Visual: https://user-images.githubusercontent.com/103560761/164251600-a19f11d5-ec51-474f-b261-fe5fd70c5a1a.mp4

Also, We would require an SVG icon for the time-series chart to be shown in the dropdown.

Thanks!
