### ISSUE TITLE
Geomap chart support in event analytics

### ISSUE THREAD

**Issue by pratibhapandey16** [opensearch-project/observability#681]
1. Add Geomap chart as a dropdown option. Refer dropdown element on top right corner of image.
2. On selection of it, it should render a Geomap chart based on data selected.
3. If data does not have timestamp information , show `no record found` message.
![Capture2](https://user-images.githubusercontent.com/103417380/164626846-91f87db9-aef5-422b-b911-65c74cf3192a.JPG)

**Comment by mengweieric** [comment]
Closed as duplicated issue same as #984
