### ISSUE TITLE
Network Diagram chart support in event analytics

### ISSUE THREAD

**Issue by pratibhapandey16** [opensearch-project/observability#682]
1. Add Network diagram chart as a dropdown option. Refer dropdown element on top right corner of image.
2. On selection of it, it should render a Network diagram chart based on data selected.
3. If data does not have timestamp information , show `no record found` message.
![Capture2](https://user-images.githubusercontent.com/103417380/164627800-dffc0f88-2cff-4c45-9e7e-f1a6c2b61ffa.JPG)

**Comment by mengweieric** [comment]
Hi @pratibhapandey16 ,

We exclude network diagram for 3.0 release.
