### ISSUE TITLE
Drag and Drop functionality in Table view

### ISSUE THREAD

**Issue by pratibhapandey16** [opensearch-project/observability#692]
- Drag and drop functionality is not working properly when we have only two columns in a query.
- Not able to rearrange the columns under table view when there are only two options.

![image](https://user-images.githubusercontent.com/103417380/165579214-ca186680-6e51-4083-bafa-89e27ab085ab.png)

**Comment by pratibhapandey16** [comment]
@mengweieric @anirudha, can you please look at the issue.

**Comment by anirudha** [comment]
nice!!!

**Comment by anirudha** [comment]
depends on #733

**Comment by pratibhapandey16** [comment]
Closing this bug as its been taken care in issue #772
