### ISSUE TITLE
The Pagination links for 'Table View' not working.

### ISSUE THREAD

**Issue by nidhisinghai** [opensearch-project/observability#696]
**What is the bug?**
The Pagination links for 'Table View' on visualization page is not working.

**How can one reproduce the bug?**

1. Go to 'Observability->Event Analytics->Explorer
2. Enter the PPL Query, Click on Refresh Button
3. Navigate to 'visualization' page  
4. Click on 'Table View' Toggle button
5. At the end on Table, click on the pagination link and observe the Issue

**What is the expected behavior?**
The Pagination number links should work properly

**Do you have any additional context?**
NOTE: The Pagination arrow links are working properly.
<img width="604" alt="image" src="https://user-images.githubusercontent.com/103416937/165903283-c5d4df01-82ee-4663-a447-8c9e5fe56524.png">

**Comment by nidhisinghai** [comment]
@mengweieric @anirudha

Please look at the Issue.

Thanks and Regards,
Nidhi Singhai

**Comment by mengweieric** [comment]
Hi @ruchika-narang,

We cannot use eui with versions newer than 34 as those are licensed with elastic license other than apache license. Check [this](https://github.com/elastic/eui/pull/4930)

In this case we need to find other ways to implement the data view table.

**Comment by nidhisinghai** [comment]
AG-Grid table does not have this issue
