### ISSUE TITLE
Implementation of Visualizations

### ISSUE THREAD

**Issue by pratibhapandey16** [opensearch-project/observability#697]
Implementation of Visualizations mentioned in the below issue
#670 
Refer to the [Chart type & config] and [Design example] sections for better understanding 

- [ ] Analysis
- [ ] Basic UI for styles
- [ ] UI and functionality of headers

![image](https://user-images.githubusercontent.com/103417380/165934816-ffe1777c-f5e3-405d-9db7-b12c6ebe3240.png)
![image](https://user-images.githubusercontent.com/103417380/165934729-77f71845-249c-4c44-a86b-126451c23ac1.png)
![image](https://user-images.githubusercontent.com/103417380/165934758-de735264-ac21-4c59-be75-5c6f3a9e6754.png)

**Comment by mengweieric** [comment]
[WIP] Config Options for all visualizations:

**Panel Options**

- Title
- Description

Value options

- xaxis
- yaxis
- zaxis
- label
- value

**Legend**

- Enabled / Disabled
- Positions
    - Bottom / right

**Chart styles**

- Orientation
- Type (mode)
- Width / size
- Fill opacity
- Label rotator
    - Rotate label when it’s too long and (or) overlaps with other labels or hidden by border
- Color theme
    - Filled area
    - graph

**Comment by ruchika-narang** [comment]
Hi @mengweieric @btzeng

The video shows the implementation of legend for bar graph. I have a question here, should we have some default values selected for Enabled/Disabled and position? If yes, should I make the Show legend **Enabled** and position set to **Right**?

https://user-images.githubusercontent.com/79983862/167145679-68dd10c9-a50f-414f-89dd-0d8c75d195e8.mp4

Also wanted to know, there are other fields like Mode, Legend values included in legend in issue #670 . Should I include them as well here?
Thanks!
@abasatwar @spattnaik

**Comment by rinku-kumar-psl** [comment]
Hi @anirudha @mengweieric @btzeng ,

The video shows the visuals and implementation of new Data configs on the Line chart as per issue #697.
The features included are:
    - Mode
    - Interpolation 
    - Line Width
    - Fill Opacity
    - Point Size
    - Bar Alignment(UI)
    - Legend
    
Please have a look and provide your suggestions or let us know any changes required for this implementation till now.

https://user-images.githubusercontent.com/103560761/168118668-24d2270d-de7a-4b21-8f15-9eae69155ae4.mp4

@mengweieric @btzeng,
I have a query under the Chart style section as in this issue there are two similar UI listed
-  Fill opacity
-  Filled area
So feature-wise what will be the difference between these two?

Thanks,
Rinku Kumar

@spattnaik @abasatwar

**Comment by ruchika-narang** [comment]
Hey @btzeng @mengweieric 

Following is the implementation of heatmap color theme. Let me know if any changes are required.

https://user-images.githubusercontent.com/79983862/170502152-e76f310e-59d9-493e-9421-4ff95d3deeda.mp4

Thanks!!

**Comment by btzeng** [comment]
@ruchika-narang   both spectrum and opacity look good. Thanks.

**Comment by rinku-kumar-psl** [comment]
Hi @mengweieric @btzeng ,

The video shows the visuals and implementation of new Data configs on the Bar chart as per this ticket.
The features included are:

Legend:
- Show Legend
- Position

Chart styles:
- Orientation(Vertical, Horizontal)
- Mode (Stack, Group)
- Rotate bar labels
- Group width
- Bar width
- Line Width
- Fill Opacity

Color Theme

Please have a look and provide your suggestions or let us know any changes required for this implementation till now.

https://user-images.githubusercontent.com/103560761/171350280-3f148dab-fcb3-4a00-8d99-312f5afad617.mp4

Note: As there is no Bar radius control option available on Plotly, So this feature is not included in this implementation.

Thanks,
Rinku Kumar

@anirudha @spattnaik @abasatwar

**Comment by ruchika-narang** [comment]
Hey @btzeng @mengweieric 
We have grabbed the color palettes from this link. https://plotly.com/javascript/reference/treemap/#treemap-marker-colorscale.
Thanks!
