### ISSUE TITLE
The Sorting for 'Table View' on visualization page not working properly.

### ISSUE THREAD

**Issue by nidhisinghai** [opensearch-project/observability#700]
**What is the bug?**
The Sorting for 'Table View' on visualization page not working properly.

**How can one reproduce the bug?**

1. Go to 'Observability->Event Analytics->Explorer
2. Enter the PPL Query, Click on Refresh Button
3. Navigate to 'visualization' page
4. Click on 'Table View' Toggle button
5. Click on  first column name from 'Header' of the table
6. Click 'Move right' -> the column gets move to right 
7.  Now click on second column from 'Header' of the table
8.  Click 'Move left' -> This Command wont work here

**What is the expected behavior?**
At Step 8 the Command 'Move left' should work  properly

Note:- only the first command either 'Move left' or 'Move right' works for a specific column whichever gets hit at first attempt.

<img width="601" alt="image" src="https://user-images.githubusercontent.com/103416937/166193559-69d66b11-3ac2-4216-a222-7e0633ee3898.png">

Best Regards,
Nidhi SINGHAI 

cc : @abasatwar @spattnaik

**Comment by mengweieric** [comment]
Hi @nidhisinghai,

Thanks for reporting this, could you check if this is a bug in EUI?

**Comment by nidhisinghai** [comment]
New AG-Grid table is introduced which does not have this issue
