### ISSUE TITLE
Snapshot test cases check fails on git hub due to time zone change

### ISSUE THREAD

**Issue by pratibhapandey16** [opensearch-project/observability#721]
Git hub check fails for Snapshot test cases due to time zone change.

**Comment by abasatwar** [comment]
Hi @mengweieric ,
Below are the steps to fix this issue on `windows`
1.node version needed - node 16.2.0 and above
2.In package.json
```
"jest": {
    "globalSetup": "../global-setup.js"
  }
```
3.In global-setup.js
```
module.exports = async () => {
    process.env.TZ = 'UTC';
};
```
For mac os  and wsl , it works fine with `process.env.TZ = 'UTC';`which is already present.

Let us know your thoughts on above solution.

cc :@anirudha  @spattnaik


Thanks,
Amruta

**Comment by mengweieric** [comment]
We are currently using node 14

**Comment by mengweieric** [comment]
Hi @pratibhapandey16,

We are using node 14 now and it's not up to us to upgrade node versions based on our needs.

**Comment by abasatwar** [comment]
hi @mengweieric ,
As per our discussion , closing this ticket as we can run test cases on mac/wsl.

Thanks,
Amruta
