### ISSUE TITLE
Apache logs support in  Observability

### ISSUE THREAD

**Issue by nidhisinghai** [opensearch-project/observability#728]
Hello @abhaypersistent 

The issue involves the below following implementations:

1. Analysis and creation on metadata
2. Index creation
3. Specs creation
4. Generating dummy data for development

Thank You,
cc : @abasatwar @spattnaik

**Comment by kuldeepbhise** [comment]
Hi @anirudha 
As part of custom log, we have made some changes in config file. i.e apache2.conf
**Step 1.** We have added below log format entry, which will help to get metadata from the server.

LogFormat " {\"timestamp\":\"%{%d/%b/%Y %T}t.%{msec_frac}t %{%z}t\", \"process_time_taken_microseconds\":\"%D\", \"filename\":\"%f\", \"remoteIP\":\"%a\", \"host\":\"%V\", \"request_url\":\"%U\", \"query\":\"%q\", \"request_method\":\"%m\", \"redirected_request_status\":\"%>s\", \"userAgent\":\"%{User-agent}i\", \"referer\":\"%{Referer}i\", \"localIP\":\"%A\", \"cookie_varname\":\"%{VARNAME}C\", \"content_of_varname\":\"%{VARNAME}e\", \"remote_host_name\":\"%h\", \"request_protocol\":\"%H\", \"keepalive_request\":\"%k\", \"remote_logname\":\"%l\", \"canonical_port\":\"%p\", \"query_string\":\"%q\", \"first_line_request\":\"%r\", \"time_to_serve_Request\":\"%T\", \"authenticated_user\":\"%u\", \"canonical_servername\":\"%v\", \"connection_response_status\":\"%X\", \"byte_received\":\"%I\", \"byte_sent\":\"%O\", \"pid_child\":\"%P\", \"thread_id\":\"%{format}P\", \"status\":\"%s\" }" custom

**Step2.** Updated the fluentd conf file with below code (i.e. /home/kbhise/fluent/fluent.conf)
<source>
@type tail
 <parse>
   @type json
   types bytes_sent:integer,byte_received:integer
   #time_key time
   #time_format %time
   #time_format %d/%b/%Y:%H:%M:%S %z
  </parse>
 path /var/log/apache2/custom.log
 pos_file /home/kbhise/apache_pos2
 tag  apache2
</source>
Note: Source block specifies the path and type from where logs should be read. Here, logs are coming in the json format.

<match apache2>
 @type opensearch
 ssl_verify false
 host localhost
 port 9200
 index_name apache_log_final
 verify_os_version_at_startup false
 suppress_type_name true
 #include_timestamp true
</match>
Note: match block specifies the destination to deliver the logs. 

**Step 3:** Once we start the fluentd and apache server, opensearch will read the logs and create the index.

**Comment by kuldeepbhise** [comment]
Hi @anirudha
As part of custom log, we have made some changes in config file. i.e apache2.conf
Step 1. We have added below log format entry, which will help to get metadata from the server.

LogFormat " {"timestamp":"%{%d/%b/%Y %T}t.%{msec_frac}t %{%z}t", "process_time_taken_microseconds":"%D", "filename":"%f", "remoteIP":"%a", "host":"%V", "request_url":"%U", "query":"%q", "request_method":"%m", "redirected_request_status":"%>s", "userAgent":"%{User-agent}i", "referer":"%{Referer}i", "localIP":"%A", "cookie_varname":"%{VARNAME}C", "content_of_varname":"%{VARNAME}e", "remote_host_name":"%h", "request_protocol":"%H", "keepalive_request":"%k", "remote_logname":"%l", "canonical_port":"%p", "query_string":"%q", "first_line_request":"%r", "time_to_serve_Request":"%T", "authenticated_user":"%u", "canonical_servername":"%v", "connection_response_status":"%X", "byte_received":"%I", "byte_sent":"%O", "pid_child":"%P", "thread_id":"%{format}P", "status":"%s" }" custom

Step2. Updated the fluentd conf file with below code (i.e. /home/kbhise/fluent/fluent.conf)


<source>
@type tail
 <parse>
   @type json
   types bytes_sent:integer,byte_received:integer
   #time_key time
   #time_format %time
   #time_format %d/%b/%Y:%H:%M:%S %z
  </parse>
 path /var/log/apache2/custom.log
 pos_file /home/kbhise/apache_pos2
 tag  apache2
</source>

Note: Source block specifies the path and type from where logs should be read. Here, logs are coming in the json format.

<match apache2>
 @type opensearch
 ssl_verify false
 host localhost
 port 9200
 index_name apache_log_final
 verify_os_version_at_startup false
 suppress_type_name true
 #include_timestamp true
</match>
Note: match block specifies the destination to deliver the logs.

Step 3: Once we start the fluentd and apache server, opensearch will read the logs and create the index.

**Comment by kuldeepbhise** [comment]
<source>
@type tail
 <parse>
   @type json
   types bytes_sent:integer,byte_received:integer
   #time_key time
   #time_format %time
   #time_format %d/%b/%Y:%H:%M:%S %z
  </parse>
 path /var/log/apache2/custom.log
 pos_file /home/kbhise/apache_pos2
 tag  apache2
</source>

**Comment by kuldeepbhise** [comment]
Hi @anirudha
As part of custom log, we have made some changes in config file. i.e apache2.conf
**Step 1**  We have added below log format entry, which will help to get metadata from the server.

LogFormat " {"timestamp":"%{%d/%b/%Y %T}t.%{msec_frac}t %{%z}t", "process_time_taken_microseconds":"%D", "filename":"%f", "remoteIP":"%a", "host":"%V", "request_url":"%U", "query":"%q", "request_method":"%m", "redirected_request_status":"%>s", "userAgent":"%{User-agent}i", "referer":"%{Referer}i", "localIP":"%A", "cookie_varname":"%{VARNAME}C", "content_of_varname":"%{VARNAME}e", "remote_host_name":"%h", "request_protocol":"%H", "keepalive_request":"%k", "remote_logname":"%l", "canonical_port":"%p", "query_string":"%q", "first_line_request":"%r", "time_to_serve_Request":"%T", "authenticated_user":"%u", "canonical_servername":"%v", "connection_response_status":"%X", "byte_received":"%I", "byte_sent":"%O", "pid_child":"%P", "thread_id":"%{format}P", "status":"%s" }" custom

**Step2**  Updated the fluentd conf file with below code (i.e. /home/kbhise/fluent/fluent.conf)
`<source>
@type tail
 <parse>
   @type json
   types bytes_sent:integer,byte_received:integer
   #time_key time
   #time_format %time
   #time_format %d/%b/%Y:%H:%M:%S %z
  </parse>
 path /var/log/apache2/custom.log
 pos_file /home/kbhise/apache_pos2
 tag  apache2
</source>`

`<match apache2>
 @type opensearch
 ssl_verify false
 host localhost
 port 9200
 index_name apache_log_final
 verify_os_version_at_startup false
 suppress_type_name true
 #include_timestamp true
</match>`

**Step 3** Once we start the fluentd and apache server, opensearch will read the logs and create the index.
![Apache2_custom_log_index](https://user-images.githubusercontent.com/105786991/172585713-887237bc-3f45-4cf0-8733-4ec5de64be60.png)

**Comment by kuldeepbhise** [comment]
Hi @anirudha,
We have created the Apache2 dashboard which is having few visualization examples. Please find video given below.


https://user-images.githubusercontent.com/105786991/172591880-128066b2-cb0e-4106-ac87-3cd930251a22.mp4


CC: @abasatwar @spattnaik

**Comment by kuldeepbhise** [comment]
Configuring Fluent-bit to read apache2 logs.

**Comment by kuldeepbhise** [comment]
Hi @anirudha, 
We have configured the fluent-bit to ingest apache2 logs. (access.log and custom.log)
1. To read access.log (default), We have used default regex format for reading and writing the logs.
     File List:

fluent-bit.conf:
```
    # Parsers File
    # ============
    # specify an optional 'Parsers' configuration file
    parsers_file parsers.conf
```

```
 [INPUT]
    Name tail
    Path /var/log/apache2/access.log
    Tag  apache_demo

[FILTER]
    Name parser
    Match apache_demo
    Parser apache2
    Key_Name log
    Reserve_Data True

[OUTPUT]
    Name  opensearch
    Match *
    Host  0.0.0.0
    Port  9200
    Index fluent-bit_apache2_accesslog
    Suppress_Type_Name on
```
   parsers.conf:
```
[PARSER]
Name   apache2
Format regex
Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^ ]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>.*)")?$
Time_Key time
Time_Format %d/%b/%Y:%H:%M:%S %z
```

2.To read custom log, We have explicitly mentioned the json format for reading and writing the logs.
fluent-bit.conf:

```
 [INPUT]
    Name tail
    Path /var/log/apache2/custom.log
    Tag  apache_demo
    parser apache2

[OUTPUT]
    Name  opensearch
    Match *
    Host  0.0.0.0
    Port  9200
    Index fluent-bit_apache2_custom_log
    Suppress_Type_Name on
```
   parsers.conf:
```
[PARSER]
    Name apache2
    Format json
    Time_Key time
```
Result:
Index created in the opensearch:

```
      {
        "_index" : "fluent-bit_apache2_custom_log",
        "_id" : "X6t-XIEBBfyf-hDPJVp0",
        "_score" : 1.0,
        "_source" : {
          "@timestamp" : "2022-06-13T09:56:19.609Z",
          "timestamp" : "13/Jun/2022 15:26:18.481 +0530",
          "process_time_taken_microseconds" : "1128427",
          "filename" : "/var/www/wordpress/index.php",
          "remoteIP" : "172.24.176.1",
          "host" : "172.24.191.180",
          "request_url" : "/index.php",
          "query" : "",
          "request_method" : "GET",
          "redirected_request_status" : "200",
          "userAgent" : "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36",
          "referer" : "-",
          "localIP" : "172.24.191.180",
          "cookie_varname" : "-",
          "content_of_varname" : "-",
          "remote_host_name" : "172.24.176.1",
          "request_protocol" : "HTTP/1.1",
          "keepalive_request" : "0",
          "remote_logname" : "-",
          "canonical_port" : "80",
          "query_string" : "",
          "first_line_request" : "GET / HTTP/1.1",
          "time_to_serve_Request" : "1",
          "authenticated_user" : "-",
          "canonical_servername" : "test-wordpress.com",
          "connection_response_status" : "+",
          "byte_received" : "455",
          "byte_sent" : "10168",
          "pid_child" : "2850",
          "thread_id" : "format",
          "status" : "200",
          "Peer_IP" : "172.24.176.1",
          "response_size" : "9839",
          "header_line" : "-",
          "log_error_request_id" : "-",
          "varname_content" : "-",
          "client_port" : "format",
          "note_varname_content" : "-",
          "handler_resonse" : "application/x-httpd-php",
          "time" : "format",
          "time_taken_to_serve_request" : "UNIT",
          "servername" : "172.24.191.180",
          "content_varname_request" : "-",
          "content_varname_response" : "-"
        }
      },
      {
        "_index" : "fluent-bit_apache2_custom_log",
        "_id" : "YKt-XIEBBfyf-hDP7Fqp",
        "_score" : 1.0,
        "_source" : {
          "@timestamp" : "2022-06-13T09:57:10.785Z",
          "timestamp" : "13/Jun/2022 15:27:10.783 +0530",
          "process_time_taken_microseconds" : "1023",
          "filename" : "-",
          "remoteIP" : "172.24.176.1",
          "host" : "test-wordpress.com",
          "request_url" : "-",
          "query" : "",
          "request_method" : "-",
          "redirected_request_status" : "408",
          "userAgent" : "-",
          "referer" : "-",
          "localIP" : "172.24.191.180",
          "cookie_varname" : "-",
          "content_of_varname" : "-",
          "remote_host_name" : "172.24.176.1",
          "request_protocol" : "HTTP/1.0",
          "keepalive_request" : "0",
          "remote_logname" : "-",
          "canonical_port" : "80",
          "query_string" : "",
          "first_line_request" : "-",
          "time_to_serve_Request" : "0",
          "authenticated_user" : "-",
          "canonical_servername" : "test-wordpress.com",
          "connection_response_status" : "-",
          "byte_received" : "0",
          "byte_sent" : "0",
          "pid_child" : "2851",
          "thread_id" : "format",
          "status" : "408",
          "Peer_IP" : "172.24.176.1",
          "response_size" : "0",
          "header_line" : "-",
          "log_error_request_id" : "-",
          "varname_content" : "-",
          "client_port" : "format",
          "note_varname_content" : "-",
          "handler_resonse" : "-",
          "time" : "format",
          "time_taken_to_serve_request" : "UNIT",
          "servername" : "test-wordpress.com",
          "content_varname_request" : "-",
          "content_varname_response" : "-"
        }
      },
      {
        "_index" : "fluent-bit_apache2_custom_log",
        "_id" : "Yat_XIEBBfyf-hDP01oi",
        "_score" : 1.0,
        "_source" : {
          "@timestamp" : "2022-06-13T09:58:09.590Z",
          "timestamp" : "13/Jun/2022 15:28:08.433 +0530",
          "process_time_taken_microseconds" : "1156415",
          "filename" : "/var/www/wordpress/index.php",
          "remoteIP" : "172.24.176.1",
          "host" : "172.24.191.180",
          "request_url" : "/index.php",
          "query" : "",
          "request_method" : "GET",
          "redirected_request_status" : "200",
          "userAgent" : "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36",
          "referer" : "-",
          "localIP" : "172.24.191.180",
          "cookie_varname" : "-",
          "content_of_varname" : "-",
          "remote_host_name" : "172.24.176.1",
          "request_protocol" : "HTTP/1.1",
          "keepalive_request" : "0",
          "remote_logname" : "-",
          "canonical_port" : "80",
          "query_string" : "",
          "first_line_request" : "GET / HTTP/1.1",
          "time_to_serve_Request" : "1",
          "authenticated_user" : "-",
          "canonical_servername" : "test-wordpress.com",
          "connection_response_status" : "+",
          "byte_received" : "455",
          "byte_sent" : "10168",
          "pid_child" : "2855",
          "thread_id" : "format",
          "status" : "200",
          "Peer_IP" : "172.24.176.1",
          "response_size" : "9839",
          "header_line" : "-",
          "log_error_request_id" : "-",
          "varname_content" : "-",
          "client_port" : "format",
          "note_varname_content" : "-",
          "handler_resonse" : "application/x-httpd-php",
          "time" : "format",
          "time_taken_to_serve_request" : "UNIT",
          "servername" : "172.24.191.180",
          "content_varname_request" : "-",
          "content_varname_response" : "-"
        }
      },
      {
        "_index" : "fluent-bit_apache2_custom_log",
        "_id" : "YquAXIEBBfyf-hDPmlpd",
        "_score" : 1.0,
        "_source" : {
          "@timestamp" : "2022-06-13T09:59:00.864Z",
          "timestamp" : "13/Jun/2022 15:29:00.863 +0530",
          "process_time_taken_microseconds" : "223",
          "filename" : "-",
          "remoteIP" : "172.24.176.1",
          "host" : "test-wordpress.com",
          "request_url" : "-",
          "query" : "",
          "request_method" : "-",
          "redirected_request_status" : "408",
          "userAgent" : "-",
          "referer" : "-",
          "localIP" : "172.24.191.180",
          "cookie_varname" : "-",
          "content_of_varname" : "-",
          "remote_host_name" : "172.24.176.1",
          "request_protocol" : "HTTP/1.0",
          "keepalive_request" : "0",
          "remote_logname" : "-",
          "canonical_port" : "80",
          "query_string" : "",
          "first_line_request" : "-",
          "time_to_serve_Request" : "0",
          "authenticated_user" : "-",
          "canonical_servername" : "test-wordpress.com",
          "connection_response_status" : "-",
          "byte_received" : "0",
          "byte_sent" : "0",
          "pid_child" : "2847",
          "thread_id" : "format",
          "status" : "408",
          "Peer_IP" : "172.24.176.1",
          "response_size" : "0",
          "header_line" : "-",
          "log_error_request_id" : "-",
          "varname_content" : "-",
          "client_port" : "format",
          "note_varname_content" : "-",
          "handler_resonse" : "-",
          "time" : "format",
          "time_taken_to_serve_request" : "UNIT",
          "servername" : "test-wordpress.com",
          "content_varname_request" : "-",
          "content_varname_response" : "-"
        }
      }
    ]
  }
}

```

**Comment by nidhisinghai** [comment]
Completed
