### ISSUE TITLE
[ENHANCEMENT]: Heatmap visualization config panel features v1

### ISSUE THREAD

**Issue by ruchika-narang** [opensearch-project/observability#791]
Implementation of Heatmap config panel features as mentioned in #787 .

Features to implement:
1. Panel options
- Use common panel options.

2. Data configurations
- Use common data configurations for heatmap, but supports only 2 dimensions.

3. Graph styles
- Colors
   - Scheme

- Legend placement ([filter buttons](https://eui.elastic.co/#/forms/filter-group))

  - bottom
  - right

**Comment by ruchika-narang** [comment]
Hi @mengweieric 

For data configurations you have mentioned to support only 2 dimensions, but the in the current implementation of heatmap we have only one value option as z-axis. So are you referring to z-axis as dimensions or is there some other term for it. Also do we have to implement x-axis, y-axis and z-axis as data configurations for heatmap?

Thanks!
CC: @abasatwar @spattnaik

**Comment by ruchika-narang** [comment]
Hi @mengweieric @anirudha 

I started working on legend for heatmap that is colorbar as per plotly's documentation. The current version of plotly that we are using(2.4.1), changing colorbar orientation is not supported yet. The Plotly provides support for colorbar orientation after version 2.8.0. So I have implemented show/hide of legend only. Let me know if that is okay.

Thanks!

CC: @abasatwar @spattnaik

**Comment by ruchika-narang** [comment]
Hi @mengweieric 

Just wanted to confirm with you if we should move the value options for this graph to the right or let them be as in screenshot.
<img width="940" alt="heatmap_dimensions" src="https://user-images.githubusercontent.com/79983862/174306277-039b3525-5f89-4756-b2aa-de55bb286402.png">

Thanks!

**Comment by ruchika-narang** [comment]
Hi @mengweieric 

Just wanted to confirm one thing about this graph, as per our Thursday's call we would display no graph. Following will be the view on the initial load. Please let me know if this is expected.

<img width="959" alt="heatmap_no_data" src="https://user-images.githubusercontent.com/79983862/174537605-496561d7-8985-4f1f-9bea-f1447b5f36f2.png">

Thanks!

**Comment by anirudha** [comment]
yes, graph only works if we the relevant data and config

**Comment by ruchika-narang** [comment]
This has been merged to the main branch in the PR: https://github.com/opensearch-project/observability/pull/824. 
Legend placement is remaining for which a separate ticket will be created and will be linked to this one.
