### ISSUE TITLE
[Enhancement]: Bar chart - Visualizations config panel features v1

### ISSUE THREAD

**Issue by abasatwar** [opensearch-project/observability#792]
Implementation of bar chart visualizations config panel features v1 according to [#787](url)

Feature requested - 
Panel options
Use common panel options.

Data configurations
Use common data configurations for bar chart, and vertical / horizontal mode swaps dimensions and metrics

Graph styles
Orientation filter ([filter buttons](https://eui.elastic.co/#/forms/filter-group))

Vertical (default)
horizontal
Type (mode) filter ([filter buttons](https://eui.elastic.co/#/forms/filter-group))

Default
Group
Stack
Legend placement ([filter buttons](https://eui.elastic.co/#/forms/filter-group))

bottom
right
Label size ([number field](https://eui.elastic.co/#/forms/form-controls#number-field))
Label rotator ([range slider](https://eui.elastic.co/#/forms/range-sliders))

-90 - 90

**Comment by abasatwar** [comment]
Hi @btzeng  , @mengweieric  ,
Please refer below images and confirm which UI representation we are referring when we say multiple metric support.
<img width="960" alt="mulitple-y-axis-values" src="https://user-images.githubusercontent.com/78089449/175063303-7124b513-d8ed-4377-a2b5-7aef98134009.png">
<img width="960" alt="multiple-yaxis" src="https://user-images.githubusercontent.com/78089449/175063232-c5f82c7a-58b4-424e-a616-60d4cee98fbe.png">

cc: @[spattnaik](https://github.com/spattnaik)
Thanks,
Amruta

**Comment by anirudha** [comment]
this look awesome! 2nd one is best!

**Comment by btzeng** [comment]
Hello Amruta,

If you’re asking which data configuration UI we should go with, it’s the 2nd one that has the 2 column layout in the left panel.
In terms of multiple fields under metric, the filed selection should be listed under the title Metrics. See https://github.com/opensearch-project/observability/issues/670

Best,
Bright

From: abasatwar ***@***.***>
Reply-To: opensearch-project/observability ***@***.***>
Date: Wednesday, June 22, 2022 at 8:07 AM
To: opensearch-project/observability ***@***.***>
Cc: "Tzeng, Bright" ***@***.***>, Mention ***@***.***>
Subject: Re: [opensearch-project/observability] [Enhancement]: Bar chart - Visualizations config panel features v1 (Issue #792)


Hi @btzeng<https://github.com/btzeng> , @mengweieric<https://github.com/mengweieric> ,
Please refer below images and confirm which UI representation we are referring when we say multiple metric support.
[mulitple-y-axis-values]<https://user-images.githubusercontent.com/78089449/175063303-7124b513-d8ed-4377-a2b5-7aef98134009.png>
[multiple-yaxis]<https://user-images.githubusercontent.com/78089449/175063232-c5f82c7a-58b4-424e-a616-60d4cee98fbe.png>

cc: @spattnaik<https://github.com/spattnaik>
Thanks,
Amruta

**Comment by abasatwar** [comment]
this is merged in sprint2 Pr.Closing this.
