### ISSUE TITLE
[Enhancement]: Time Series - Visualizations config panel features v1 

### ISSUE THREAD

**Issue by abasatwar** [opensearch-project/observability#794]
Implementation of Time Series visualizations config panel features v1 according to [#787](https://github.com/opensearch-project/observability/issues/url)

Panel options
Use common panel options.

Data configurations
Use common data configurations for timeseries chart, and the first dimension is always timestamp by default.

Graph styles
Type (mode) selector ([filter buttons](https://eui.elastic.co/#/forms/filter-group))
Markers
Lines
Lines + markers
Line width ([range slider](https://eui.elastic.co/#/forms/range-sliders))
1 - 10px
Fill opacity ([range slider](https://eui.elastic.co/#/forms/range-sliders))
0 - 100%
color picker (palette selector)
Legend size ([number field](https://eui.elastic.co/#/forms/form-controls#number-field))
Label size ([number field](https://eui.elastic.co/#/forms/form-controls#number-field))
Label rotator
Rotate label when it’s too long and (or) overlaps with other labels or hidden by border
-90 - 90

**Comment by abasatwar** [comment]
Hi @mengweieric ,
We have few queries related to this implementation -
Dimensions:
- Can user select a timestamp and non-timestamp field there? And if yes then how the visualization will be plotted?
- If user select 2 or more dimensions then do we have to render all dimension value on dimension axis(x-axis).?
- And for time-series visualization there should be only timestamp field to select in dimension?
- Will Data configuration panel only render on Visualization tab click or this will be common for event tab too?
cc: @anirudha @spattanaik @rinku-kumar-psl 


thanks,
Amruta

**Comment by nidhisinghai** [comment]
Completed
