### ISSUE TITLE
[ENHANCEMENT]: TreeMap visualization config panel features v1

### ISSUE THREAD

**Issue by mrunal-z** [opensearch-project/observability#796]
This ticket is an enhancement to #664. This will have more features for config panel as mentioned in #787.

Features to implement:

**Panel options**
Use common panel options.

**Data configurations**
Group by
Group by section defines all groups for rendering a treemap. User clicks add button to add group as parent level, child level, ground child level, ..., whose hierarchy is denoted by the order of the groups added. UI allows user to drag and drop to reorder to visualize new treemap.

**Graph styles**
Colors
- Scheme

Legend placement ([filter buttons](https://eui.elastic.co/#/forms/filter-group))
- bottom
- right

**Comment by mrunal-z** [comment]
Hey @mengweieric - 
1. You have specified Legend placement options here, but treemap doesn't have support for a legend, so should we remove this? 
2. In data configurations, will we also have metrics which define the value field or will the first/last field in Group By section be considered as the value field?

Thanks!
@abasatwar @spattnaik

**Comment by mrunal-z** [comment]
Hi @mengweieric 

Following is the demo video for treemap multiple parents implementation, with color theme. Let me know if anything else is required. 

https://user-images.githubusercontent.com/79525611/174304148-3b659d35-48e1-4047-96c7-5777a82a9432.mp4

Thanks!

**Comment by nidhisinghai** [comment]
Completed
