### ISSUE TITLE
[Enhancement]: UI for dimension and metrics

### ISSUE THREAD

**Issue by abasatwar** [opensearch-project/observability#797]
Implementation of UI according to [#787](https://github.com/opensearch-project/observability/issues/url) features.
features - 
1.UI for dimensions
2.UI for metrics
[https://user-images.githubusercontent.com/93013804/172738758-c9702c1f-1b41-4ac2-9b09-095a13632180.png](url)

<img width="716" alt="image" src="https://user-images.githubusercontent.com/78089449/173083922-5325d08f-1273-4fa8-845e-9c3f8eb91f85.png">

**Comment by btzeng** [comment]
@deepaknevdepsl  Please make sure the left and right padding (shown in red) is 10px, right now in the video you provided, it looks huge. 
<img width="530" alt="padding" src="https://user-images.githubusercontent.com/93013804/175427751-fe7dc6ec-ada6-48b0-80e2-c5d28d12033e.png">

**Comment by abasatwar** [comment]
This is completed in sprint2.Hence closing this.
