### ISSUE TITLE
Separate OpenSearch and OpenSearch Dashboards plugins into their own repos

### ISSUE THREAD

**Issue by dblock** [opensearch-project/observability#803]
**Is your feature request related to a problem?**

Coming from https://github.com/opensearch-project/opensearch-build/issues/2188, it's not possible to release and tag the OpenSearch plugin in this repo separately from the OpenSearch Dashboards plugin in this repo as, for example, `2.0.0`. This means we must release the two plugins at the same time.

**What solution would you like?**
The plugins should live in their own repos.

**What alternatives have you considered?**
A tagging scheme such as opensearch-2.0.0 vs. opensearch-dashboards-2.0.0.

**Comment by dblock** [comment]
See https://github.com/opensearch-project/opensearch-build/issues/2188#issuecomment-1259874232 in which we decided to split front-end and back-end components in v2.5.0.

**Comment by derek-ho** [comment]
@dblock this is done, so closing this issue now, thanks!
