### ISSUE TITLE
[FEATURE]:[Visualizations]"No Data Found" screen size on Visualizations page

### ISSUE THREAD

**Issue by pratibhapandey16** [opensearch-project/observability#810]
The screen size  for `No Data Found` message should be similar as the size of the chart rendered on Visualizations page.

![image](https://user-images.githubusercontent.com/103417380/174278367-0e1ec707-1f6b-4704-bbb8-71438274fea2.png)

**Comment by shankha-das** [comment]
Hi @mengweieric , @btzeng 
Just wanted to confirm about the UI about "No Data Found" and "Visualization" as per the discussion in yesterday's standup. Attaching two screenshots of "No Data Found" and "Visualization":

![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/93648901/174760686-ab69a387-9c85-43d1-a50f-54f3988e1fa7.png)

![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/93648901/174760712-8e710a11-dbe6-4e00-b9d3-73a2739c8c6b.png)

Please let me know if this looks fine to you.

Thanks!
CC: @abasatwar @spattnaik @anirudha

**Comment by shankha-das** [comment]
Hi @btzeng @mengweieric 

We have implemented the UI as mentioned in the call. But we need some inputs from you as discussed in the call. Listing those below:
1. The height of Chart Type dropdown
2. The min-height and min-width of all the sections (Field names, Data configuration, Visualization Panel, Config options)

Thanks!

CC. @abasatwar @spattnaik @ruchika-narang

**Comment by pratibhapandey16** [comment]
"No Data Found" screen size is appearing as expected on Visualization page.

![image](https://user-images.githubusercontent.com/103417380/179748843-04d0690c-254f-424c-bb0e-68dc1d30ccbc.png)

Functional testing completed for the issue.

**Comment by shankha-das** [comment]
> Hi @btzeng @mengweieric
> 
> We have implemented the UI as mentioned in the call. But we need some inputs from you as discussed in the call. Listing those below:
> 
> 1. The height of Chart Type dropdown
> 2. The min-height and min-width of all the sections (Field names, Data configuration, Visualization Panel, Config options)
> 
> Thanks!
> 
> CC. @abasatwar @spattnaik @ruchika-narang

Hi @btzeng @mengweieric 

Please let me know if there is any update on the above query.

Thanks.
