### ISSUE TITLE
Treemap colorscale

### ISSUE THREAD

**Issue by btzeng** [opensearch-project/observability#820]
@mengweieric @mrunal-z  
Please refer to plotly colorscale for treemap.
https://plotly.com/python/treemaps/
<img width="943" alt="colorscale" src="https://user-images.githubusercontent.com/93013804/175613387-e496a9c6-09f6-4cc8-8a2b-8f38b76ed981.png">

**Comment by anirudha** [comment]
@mrunal-z could you or amruta take a look , thanks

**Comment by mrunal-z** [comment]
Hi @mengweieric @anirudha @btzeng - 
I explored the colorscale for treemap as a legend option, and I have the following findings:
1. We cannot display a colorscale for the Default, Single Color, or Multicolored palette options. Colorscale is only shown when the named palettes (ex. Blues, Reds, Yellow-Orange-Red) are selected.
2. Currently, we cannot set the position of the colorbar to be horizontal (bottom), as is explained in this comment - https://github.com/opensearch-project/observability/issues/791#issuecomment-1155185565. So the colorbar position will always be vertical (right).

We can only have the show/hide legend option in the config panel for now, so please let me know if I should proceed with this implementation.

Thanks!

**Comment by mengweieric** [comment]
Resolved.
