### ISSUE TITLE
ENHANCEMENT: config panel and visualization canvas height update

### ISSUE THREAD

**Issue by nidhisinghai** [opensearch-project/observability#829]
Make heights of config panel and visualization canvas to have the same height as left hand side data configurations section, I.e to make those occupy entire space vertically

**Comment by shankha-das** [comment]
Hi @mengweieric @btzeng @anirudha 

As per the mentioned in the ticket, I have updated the height of the visualization canvas and config options. Please let me know if this looks fine to you!!
![MicrosoftTeams-image (11)](https://user-images.githubusercontent.com/93648901/177105157-10a23db5-0ed9-4fb8-9c8e-e2e678f204b9.png)

Thanks!!
@abasatwar @spattnaik
