### ISSUE TITLE
[FEATURE] Stats

### ISSUE THREAD

**Issue by ramneet-persistent** [opensearch-project/observability#835]
As per  #787, issue includes below tasks
Stats
- Common Panel Options
- Data configurations: Data configurations section for stat works the same as gauge’s. Each metric is essentially a stat and there will be no breakdowns section for Stat.
- Graph styles
   * Orientation
      - auto(horizontal)
      -  horizontal
      - vertical
   * Legend placement
   * chat mode
      - auto
      - horizontal
      - text mode
   * Title size
   * Value size
   * Series units
   * Precision value for Series
   * Text mode : Control if name and value is displayed or just name.
      - Auto
      - Value and names
      - Values
      - Names
- Thresholds
   - color based thresholds as per reference shared

**Comment by ramneet-persistent** [comment]
Hi @mengweieric, @anirudha 
Can you please confirm type of chart needed for stats.
as per previous conversations, type indicator was addressed for stats. But indicator itself has few types as mentioned below:
1. gauge
2. number
3. number/number+delta
pt.1: we have existing option of gauge in type of visualizations.
pt 2, 3: will be ruled as we need to add "text mode", removing either name or values, chart will have no meaningful output. Also we don't have delta value.

please share your inputs, it would be very helpful

cc: @abasatwar, @spattnaik

Thanks
Ramneet

**Comment by ramneet-persistent** [comment]
Hi @mengweieric, @anirudha, @btzeng 
as per previous discussion over call. time series and indicator is combined for stats chart. we followed grafana stats. few queries w.r.t implementation

1. as per #787, data configuration for stats is same as gauge chart. But with multiple dimensions, do we need to display multiple spark lines in each subplot? please refer SS for single dimension and multiple metrics.
<img width="955" alt="stats_multiple_metrics_single dimensions" src="https://user-images.githubusercontent.com/105915936/180267709-e1a4a34c-0f77-489c-829d-973c219d1547.png">
2. also with no dimensions : auto chart type will be same as horizontal/text mode.
3. Thresholds: on grafana threshold is bit confusing. so following #787 it has same threshold as per time series. considering threshold line in each subplot or single line over whole plot. also orientation change is concern here. please share your inputs.
4.  for horizontal mode as per grafana, each horizontal bar has different color, but in plotly we can't have different color for each subplot, so a workaround  is to add shapes below each subplot and add colors to it. please share your inputs on this one also.


Kindly refer attached video of stats implementation
https://user-images.githubusercontent.com/105915936/180265416-9f878d5a-2f07-4dae-b2e7-850559b804f4.mp4

please confirm implementation and share your feedback
Thanks

**Comment by NamanChaturvedi13** [comment]
Hi @ramneet-persistent 
While doing the functional testing for the stats chart , found certain observations :

1. After changing the chart type from auto to horizontal/textmode and changing it back to auto the UI is crashing .
2. For the Chart Orientation also UI is crashing for any change from auto to vertical/horizontal .
3. UI is crashing for any value entered in the Metrics Precision , value size and for the Title size as well .
4. Just like the chart orientation , changing the Text mode from its default to any other value is Crashing the UI .
5. Entering any name in the Threshold section is not reflecting in the visualization .

**Comment by ramneet-persistent** [comment]
@NamanChaturvedi13 
raised pr is only for auto chart type. will new pr for horizontal/text mode chart
UI crashes are fixed and code is updated.
Threshold labels will not reflect on plots as we are only using value and color of applied threshold
Thanks
