### ISSUE TITLE
[FEATURE] : Network Diagram chart support in event analytics

### ISSUE THREAD

**Issue by deepaknevdepsl** [opensearch-project/observability#846]
1. Add Network diagram chart as a dropdown option. Refer dropdown element on top right corner of image.
2. On selection of it, it should render a Network diagram chart based on data selected.
3. If data does not have timestamp information , show no record found message.

<img width="569" alt="image" src="https://user-images.githubusercontent.com/102342039/178267953-7c2e7c38-ff00-4d1a-a63c-cea0a2f4ec3c.png">

**Comment by deepaknevdepsl** [comment]
Hi @anirudha , @mengweieric , @btzeng 

1] Are we going to give any specific options to user for selecting source and target to generate node graph edges.?
2] Do we have any specific query to generate required node graph data which will have source and target? currently I am using this "source=opensearch_dashboards_sample_data_flights | stats count() by DestCityName, OriginCityName", It has lot of data which forms graphs as follows. Do you think this is right?
3] Do you want to give an multiple sources and target options to generate Node graph?
4] Can we use metrics and dimensions as source and target ?

<img width="960" alt="image" src="https://user-images.githubusercontent.com/102342039/178269013-f545a79a-460c-4642-8cad-e09b1e18e2d0.png">


Thanks
Deepak

@abasatwar @spattnaik

**Comment by pratibhapandey16** [comment]
As per earlier discussion this chart is not required so closing the issue.
