### ISSUE TITLE
[ENHANCEMENT-2]: Heatmap visualization config panel features v1

### ISSUE THREAD

**Issue by ruchika-narang** [opensearch-project/observability#847]
Implementation of Heatmap leftover config panel features as mentioned in #787. Linking the older enhancement issue for the reference of remaining features #791 .

Features to implement:

-  Legend placement ([filter buttons](https://eui.elastic.co/#/forms/filter-group))
   - bottom
   - right

**Comment by btzeng** [comment]
@ruchika-narang  Yes due to plotly limitation. Please make sure the orientation of the colorscale on the right hand side is vertical
