### ISSUE TITLE
Filter Logs View data 

### ISSUE THREAD

**Issue by pratibhapandey16** [opensearch-project/observability#863]
Filter the data of Logs-View according to the Available fields on the Sidebar

**Comment by shankha-das** [comment]
Hi @mengweieric , @btzeng , @anirudha 

I was working on logs view filter data on the basis of field selection from available fields and pagination. I have a few questions related to it.

1. How many options should be there in 'Rows per page'? (See the screenshot for reference)

2. When we are filtering the logs view data, should we also filter the data inside Accordion or it should display all the data? As per current implementation in Events tab log, when user selects specific fields in the flyout the whole data is visible in tabular form.

3. Please can you confirm on the UI for logs view? Currently it is implemented as in the screenshot.

![MicrosoftTeams-image (13)](https://user-images.githubusercontent.com/93648901/180449145-bcbd304e-b4d6-4616-b34b-0ad52bdc99fd.png)

Thanks,
Shankha
