### ISSUE TITLE
[BUG]: Screen gets distorted after clicking on resizable buttons on Visualization page.

### ISSUE THREAD

**Issue by pratibhapandey16** [opensearch-project/observability#865]
**What is the bug?**
1. Legends are getting distorted after dragging resizable button.
2. Data Config panel combo box icons are getting distorted after dragging resizable button.

**How can one reproduce the bug?**
1. Go to Observability/Event Analytics/Explorer page
2. Select any chart from the chart selector
3. Drag the resizable buttons that are on both the sides of the chart and observe the issue.

**What is the expected behavior?**
The legends and combo box icons should be properly aligned even after dragging the resizable buttons.

**Do you have any screenshots?**
![image](https://user-images.githubusercontent.com/103417380/179182745-a4279848-a8ef-4bfd-8f43-0d36fcd8fb82.png)

**Comment by deepaknevdepsl** [comment]
Hi @anirudha , @mengweieric , @btzeng 
We have fixed an legends overlapping issue on resize button action, now if we resize panel, then legends will adjust accordingly. Please see the attached video.


https://user-images.githubusercontent.com/102342039/181683723-7ac660cc-215b-47bd-a9c4-22dad93b611f.mp4

Please confirm is this looks good ?



Thanks
Deepak

@abasatwar @spattnaik

**Comment by pratibhapandey16** [comment]
The bug is on hold will be discussed in Bug bash.
