### ISSUE TITLE
[EXPLORATION]: Exploration on new charts in Plotly

### ISSUE THREAD

**Issue by ruchika-narang** [opensearch-project/observability#866]
Exploration on new charts and checking their feasibility to be implemented in the observability application.

**Comment by ruchika-narang** [comment]
Hi @mengweieric , @btzeng , @anirudha 
Following is the list of charts that we have explored. Please can you tell which charts we need to implement and in what priority order.

|Graph Name|Implementation Present|Description/Use case|Can be implented with Plotly|If requires other library|Documentation link|Comments(if any)|
|:----|:----|:----|:----|:----|:----|:----|
|Area|No| |Yes| | |An area is a line chart available with filled area below the line. We can add this in the graph list. Please suggest your thoughts on this one.|
|Controls|No| | | | |Can you please tell us how do we proceed with this one as we couldn't find any references of it in plotly.|
|Coordinate map|No|A coordinate map that represents the value on the graph with the latitude and longitude|Yes|No|https://plotly.com/javascript/scatter-plots-on-maps/| |
|Data Table|No| | | | |Need to add this in the dropdown for charts|
|Goal|No|A goal chart is a chart that helps us keep a track of goals. It can act as a roadmap and show us how close are we to completing the goal. |Yes|No|https://plotly.com/javascript/indicator/|We think goal chart resembles indicator in plotly. Can you please suggest if this will be the right implementation?|
|Horizontal Bar|No| |Yes|No|https://plotly.com/javascript/horizontal-bar-charts/|We have a file for type included need to check how to implement with just changing the orientation.|
|Markdown|No| | | | |There is a text dropdown in the charts. Please can you tell if we need to rename text to markdown?|
|Metric|No|Displays a single value after applying aggregations.|No|No|NA|It is not a graph it just displays a calculated single value on the basis of aggregate functions. Do we need to include this in the charts dropdown?|
|Region Map|No|It is a type of map that portrays the geographic pattern of a particular subject in a geographic area.|Yes|No|https://plotly.com/javascript/choropleth-maps/| |
|TSVB|No|Build time-series using visualise pipeline interface| | | | |
|Tag Cloud|No|A group of words sized according to their importance|No|Yes|https://www.npmjs.com/package/wordcloud|Please confirm about if we need to implement this?|
|Timeline|No|A time-series graph with functional expressions|Yes|No|https://plotly.com/javascript/time-series/|Can you please confirm about the functional expressions we need to use here or will they be custom expressions written by user? Also we are unable to run this on dashboards, it'd be great if you can guide us on the steps.|
|Vega|No|It is a visualization grammar, a declarative language for creating, saving, and sharing interactive visualization designs. With Vega, you can describe the visual appearance and interactive behavior of a visualization in a JSON format, and generate web-based views using Canvas or SVG.|No|Yes|https://vega.github.io/vega/|This is an integration and not implementation from a library. This is itself a separate library, do we have to include this?|
|Vertical Bar|No| |Yes| | |Should we rename the bar to vertical bar?|

Thanks,
Ruchika

CC: @abasatwar , @spattnaik

**Comment by anirudha** [comment]
lets do all with "Can be implented with Plotly"

**Comment by anirudha** [comment]
thanks @ruchika-narang ! this is good :)

**Comment by ruchika-narang** [comment]
We have explored multiple charts and have found a list that can be implemented in the application. So closing this ticket.
