### ISSUE TITLE
[FEATURE]: Metric chart support in event analytics

### ISSUE THREAD

**Issue by ruchika-narang** [opensearch-project/observability#872]
1. Add metric chart as a dropdown option.
2. On selection of it, it should render a metric chart based on the aggregate function selected by user.

**Comment by ruchika-narang** [comment]
Hi @mengweieric , @btzeng 

I have begun working on metric chart and I have taken reference from the dashboard. I have few questions related to it.
1. Do we have to include the sibling pipeline aggregate functions in the dropdown of aggregate function as in the below screenshot?
<img width="960" alt="aggregate_function" src="https://user-images.githubusercontent.com/79983862/180059375-7d73ab23-c0bf-4e92-8d3d-b696651bbcfc.png">

2. There is a split group section inside bucket. Do we have to include that as in screenshot?
<img width="960" alt="metric_bucket" src="https://user-images.githubusercontent.com/79983862/180060994-38eee383-31cc-44de-8137-a95497a1a833.png">

Please let me know if I am going in the right direction for metric chart implementation and we need a similar implementation as dashboard.

Thanks,
Ruchika

**Comment by ruchika-narang** [comment]
Hi @mengweieric @btzeng @anirudha 

I have started to work on Metrics chart. Currently we have included its basic implementation, which displays a single calculated value on the basis of chosen aggregate function and the UI looks as follows.
<img width="959" alt="metrics_chart" src="https://user-images.githubusercontent.com/79983862/180457331-260f58b3-1d1d-429f-9371-4963459e84a5.png">

A user can select more metrics also and it will be displayed in the same fashion along with other selected values. The reference for its implementation is from dashboard. Can you please confirm if the UI looks good to you. 

I have a few questions with related to it which are asked in the above comment. Can you please clarify them as well!

Thanks,
Ruchika

**Comment by ruchika-narang** [comment]
Hi @mengweieric , @btzeng , @anirudha 

Following is the basic implementation of metrics chart. Let me know if we to need to make any changes here.


https://user-images.githubusercontent.com/79983862/182144591-93cbcc1d-b316-4d3b-8cf6-aa780e1315a1.mp4



Thanks,
Ruchika

**Comment by SivaprasadAluri** [comment]
Hi @mengweieric , @btzeng , @anirudha

Following is the implementation of metrics chart. That includes color Theme, Title and Font size panel, Let me know if we to need to make any changes here.

https://user-images.githubusercontent.com/110654651/185618942-ad95c50f-11be-401c-b9eb-48d2a79e5edf.mp4

Thanks
Sivaprasad

**Comment by SivaprasadAluri** [comment]
Hi @mengweieric , @anirudha

Following is the implementation of metrics chart. Please let me know if any changes are needed.

https://user-images.githubusercontent.com/110654651/195015821-87eb6d6d-2799-40c0-ae02-8019cd7f2ae6.mp4

Thanks 
Sivaprasad Aluri

CC: @ruchika-narang

**Comment by ruchika-narang** [comment]
Closing this one as renaming Stats to metrics. So this ticket is not needed anymore.
