### ISSUE TITLE
[FEATURE] gauge chart: multiple thresholds

### ISSUE THREAD

**Issue by ramneet-persistent** [opensearch-project/observability#873]
multiple thresholds on gauge bar

[https://github.com/plotly/plotly.js/issues/6270](url)

**Comment by ramneet-persistent** [comment]
Issue is on hold until multiple thresholds support added in plotly gauge chart. [https://github.com/plotly/plotly.js/issues/6270](https://github.com/opensearch-project/observability/issues/url)

**Comment by ramneet-persistent** [comment]
as per discussion, Gauge only support single threshold using default implementation.
so closing this ticket

**Comment by elfisher** [comment]
@ramneet-persistent should we remove this from the roadmap?

**Comment by ramneet-persistent** [comment]
> @ramneet-persistent should we remove this from the roadmap?

Hey @mengweieric do you think we should remove it?
