### ISSUE TITLE
[FEATURE]: Annotation support for visualizations.

### ISSUE THREAD

**Issue by abasatwar** [opensearch-project/observability#874]
Here is link for  annotations - https://plotly.com/javascript/text-and-annotations/

**Comment by abasatwar** [comment]
Hi @btzeng ,
We have explored annotations in plotly and we need ui/ux for its integration. 
It is applicable to few visualizations like line, scatter, heatmap, etc.
Here is link for annotations - [https://plotly.com/javascript/text-and-annotations/](url)
Let us know if any other information is required here.

cc: @anirudha , @mengweieric 
Thanks,
Amruta

**Comment by abasatwar** [comment]
Hi @anirudha  ,
As per our discussion yesterday, this will be handled by some other team.so closing this for now.

Thanks,
Amruta

**Comment by Koustubh5585** [comment]
Added annotation support for:
- [ ] Bar Chart
- [ ] Time Series chart

**Comment by Koustubh5585** [comment]
https://user-images.githubusercontent.com/42600229/187379800-2fca6006-86c7-4caa-b3eb-e5c05326dd01.mp4

Uploaded screen recording of annotation implementation
