### ISSUE TITLE
[Event] Enable stat visualizations for prometheus PPL and promQL queries.

### ISSUE THREAD

**Issue by vamsi-amazon** [opensearch-project/observability#882]
**Is your feature request related to a problem?**
In the current state, we enable line charts only for stats queries. With the upcoming metric launches, we need to redefine this and enable it for Prometheus PPL and promQL Queries.

Eg: 
1) source=prometheus.query_range(`prometheus_http_requests_total{code='200',handler = '/-/ready'}`)
2) source=prometheus.prometheus_http_requests_total 
<img width="1792" alt="Screen Shot 2022-07-19 at 3 29 01 PM" src="https://user-images.githubusercontent.com/99925918/179859196-4ac7dd6e-71ec-4ef2-b515-a0bae73fcbca.png">
<img width="1792" alt="Screen Shot 2022-07-19 at 3 28 25 PM" src="https://user-images.githubusercontent.com/99925918/179859207-baf187ad-7b00-4bd9-aebc-4d56a49f96f4.png">

**Comment by pjfitzgibbons** [comment]
This is only front-end work.  The visualization widget only depends upon the data-frame being sent from the execution of the given PPL.  In the case of metric, that PPL (source=prometheus) will already present a "correct" dataframe
