### ISSUE TITLE
[BUG] : On click of Reset button on visualization the input field value does not gets reset.

### ISSUE THREAD

**Issue by nidhisinghai** [opensearch-project/observability#890]
**What is the bug?**
On click of Reset button on visualization the input field value does not gets reset.

**How can one reproduce the bug?**

1. Go to Observability/Event Analytics/Explorer page
2. Select any chart from the chart selector which has  Input field 
 e.g. bar chart has input field of 'Label Size'
( In Time Series 'Legend Size' and 'Label Size', Gauge has 'Title Size' and 'Value Size' like this etc.)
3. Give value as 20 for Label Size
4. click Reset

**What is the expected behavior?**
 Expected Behavior- The Label Size should set to auto
 Actual Behavior- The value remains 20 here in panel but the chart gets updated

**Do you have any screenshots?**

<img width="164" alt="image" src="https://user-images.githubusercontent.com/103416937/180387755-1343621f-afd0-4b01-b97d-38880cc6f48c.png">

@anirudha @mengweieric 
cc : @abasatwar @spattnaik

**Comment by abasatwar** [comment]
hi @btzeng  ,
Let us know your thought on keeping this reset button.
Just fyi, we have recently removed preview button. 
cc: @spattnaik , @mengweieric @anirudha 

Thanks,
Amruta

**Comment by nidhisinghai** [comment]
@btzeng @mengweieric , could you please confirm on this ?

**Comment by nidhisinghai** [comment]
issue solved
