### ISSUE TITLE
[BUG]: The default value for input field and slider are not constant for different chart

### ISSUE THREAD

**Issue by nidhisinghai** [opensearch-project/observability#896]
@anirudha @mengweieric 

**What is the bug?**
A clear and concise description of the bug.
The Default value for input field and slider are not constant for different chart

**How can one reproduce the bug?**

1. Go to Observability/Event Analytics/Explorer page
2. Go to Visualizations
3. Here the default value for input field and slider are not constant for different chart

e.g. For bar chart the default line width value is 1 and the default Fill opacity value is 80
while for time series the default line width value is 2 and the default Fill opacity value is 40

so like this can you confirm the default value for each of the input field and slider  for all charts

**What is the expected behavior?**
the value for these slider should be constant among the charts so that it can help also while creating a cypress test case we need not to take different value for different charts

**Do you have any screenshots?**
<img width="159" alt="image" src="https://user-images.githubusercontent.com/103416937/181219649-06f28421-9a47-4136-ac92-c7cb8fcd9789.png">

<img width="150" alt="image" src="https://user-images.githubusercontent.com/103416937/181219810-c41c38fb-41e7-4a52-80c7-750b8e97fd94.png">

@abasatwar @spattnaik

**Comment by pratibhapandey16** [comment]
Will be taken care in Bug bash.
