### ISSUE TITLE
TableView Chart Implementation

### ISSUE THREAD

**Issue by rinku-kumar-psl** [opensearch-project/observability#916]
Table View chart implementation in visualization.

**Comment by rinku-kumar-psl** [comment]
Hi @mengweieric , @anirudha ,

We found these below features corresponding to the Table-View mode we can add on Data config panel and working on the implementation for these features.

Please have a look and suggest what other option we can add now.

- Show table header
- Enable Pagination
- Min Counm Width
- Column Width
- Column Alignment
- Cell Display mode
- Column Filter
- Show table footer

Thanks!

**Comment by mengweieric** [comment]
Resolved.
