### ISSUE TITLE
[BUG]: scatter chart "Dimensions" takes a field even if the ppl query don't have a timestamp in it.

### ISSUE THREAD

**Issue by nidhisinghai** [opensearch-project/observability#946]
**What is the bug?**
scatter chart "Dimensions" takes a field even if the ppl query don't have a timestamp in it.

**How can one reproduce the bug?**
1. Go to observability -> Event analytics-> Explorer
2. put a ppl query as - "source = opensearch_dashboards_sample_data_logs |stats max(bytes), avg(bytes) by host"
3. click refresh
4. select the scatter chart from the list
  here we see the Dimensions field picks the host which is not a timestamp

**What is the expected behavior?**
1. the Dimension should remain disable as the query has no timestamp

2. also when the dimension is disable, the field section should show some meaningful message as " put a query which has timestamp in it"

**Do you have any screenshots?**
<img width="899" alt="image" src="https://user-images.githubusercontent.com/103416937/185337942-f2c85b28-471f-413c-9361-f036763de1b6.png">

<img width="912" alt="image" src="https://user-images.githubusercontent.com/103416937/185339211-a165e3a2-4723-426f-8024-4f246f43d5e1.png">

@abasatwar @spattnaik @ruchika-narang

**Comment by ruchika-narang** [comment]
Hi @btzeng , @mengweieric , @anirudha 

We need a confirmation for about the implementation of showing the user a warning for selecting a query which has a timestamp field to render scatter and timeseries. As per the current implementation of timeseries we will only have one dimension which will be of type "timestamp". 
Please let me know if the following implementation looks good to you? The warning sign beside the dimension will only appear on timeseries and scatter and when there is no timestamp field.

https://user-images.githubusercontent.com/79983862/185423201-0a418869-59cb-4ff3-bdec-866af8e2263a.mp4

**Comment by ruchika-narang** [comment]
Closing this one as this was resolved by implementing updated UI for data configuration.
