### ISSUE TITLE
[BUG] : Newly saved Visualization replaces the earlier one

### ISSUE THREAD

**Issue by NamanChaturvedi13** [opensearch-project/observability#947]
**What is the bug?**
On saving a new visualization the earlier saved visualization also gets replaced with the new one . Hence multiple same visualizations are seen in the operational panels section. 
Note: Happening for all charts . Also the same behaviour is seen in the event analytics section as well

**How can one reproduce the bug?**

1. Go to Observability/Event Analytics/Explorer page
2. Enter any ppl query and refresh
3. Navigate to Visualizations page
4. Select any chart type (say timeseries) and save the visualization with a name (say timeseries 1)
5. Go to operational panels -> This timeseries 1 should be present
6. Now enter a different ppl query , select timeseries chart and save as (timeseries 2)
7. Go to operational panels and observe the issue now 

**What is the expected behavior?**
All the differently named visualization must be seen in the operational panels section without overriding others .

**Do you have any screenshots?**

![Screenshot (46)](https://user-images.githubusercontent.com/78581256/185387229-b1bd322c-aa9c-4de9-958a-b25f9a53dedf.png)
![Screenshot (47)](https://user-images.githubusercontent.com/78581256/185387406-0a27e9fa-9c55-4a28-9af5-f47bb547e566.png)

@anirudha @mengweieric
cc: @abasatwar @spattnaik

**Comment by ruchika-narang** [comment]
This is an existing functionality and no changes were to this. As discussed in the sync up call closing this one. Thanks!!
