### ISSUE TITLE
[BUG]: Side option of 'Data Configuration Panel' for time series and scatter chart is not working

### ISSUE THREAD

**Issue by nidhisinghai** [opensearch-project/observability#951]
@ruchika-narang 
**What is the bug?**
Side option (Left and Right) of 'Data Configuration Panel' for time series and scatter chart is not working

**How can one reproduce the bug?**
1. Launch OpenSearch  Dashboard UI
Go to Observability->Event Analytics->Explorer
2. Enter PPL Query as 
source = opensearch_dashboards_sample_data_logs | where response='503' or response='404' | stats count() by span(timestamp,1d)
For time select "Year to date"
click "Refresh"
4.Click on "Visualizations" tab
5. Select the timeseries/scatter from the dropdown

**What is the expected behavior?**
here the Side option(left and right) of 'Data Configuration Panel' for time series and scatter chart is not working

**Do you have any screenshots?**
<img width="959" alt="image" src="https://user-images.githubusercontent.com/103416937/185558487-fb554ec9-dd06-4e81-84a6-652f5a000781.png">

@abasatwar @spattnaik

**Comment by ruchika-narang** [comment]
Closing this one as it was resolved while implementing 2 way sync for scatter.
