### ISSUE TITLE
[BUG]: Error message on Operational panel for deleted Visualizations

### ISSUE THREAD

**Issue by pratibhapandey16** [opensearch-project/observability#953]
**What is the bug?**
When we delete any saved Visualization from Event analytics a placeholder gets saved in Operational panel for the same Visualization with an error message
Error message: `Could not locate saved visualization id:NtYusYIBI6RhBGXbzQSY`

**How can one reproduce the bug?**
1. Go to Observability/Event Analytics/Explorer page
2. Navigate to Visualizations page
3. Select any chart option from chart selector dropdown
4. Save the chart with proper name and details
5. Go the Operational panel and select the saved visualization 
6. Look the saved chart details on Operational panel
7. Delete the saved chart from Event Analytics and repeat steps 5 and 6
8. Observe the issue where in place of chart details error message is visible

**What is the expected behavior?**
Chart should not be visible on Operational panel once deleted. 

**Do you have any screenshots?**
![image](https://user-images.githubusercontent.com/103417380/185595591-318dbcad-2af6-4e0d-bdc8-68983f9f9c77.png)

@anirudha @mengweieric
cc: @abasatwar @spattnaik

**Comment by abasatwar** [comment]
hi @anirudha  ,
We would like to know the priority of this bug.

Thanks,
Amruta

**Comment by ruchika-narang** [comment]
Hi @mengweieric 

As per the current implementation for operational panels, we have a condition to include the error when the saved visualization was deleted by the user from event analytics. Do we want the user to manually update the operational panel by deleting the visualization which have error or should we delete them at the same moment when the saved visualization is deleted from visualization list on event analytics?

Thanks,
Ruchika

**Comment by ruchika-narang** [comment]
Hey @mengweieric 

Can you please confirm on this one? Thanks!!

> Hi @mengweieric
> 
> As per the current implementation for operational panels, we have a condition to include the error when the saved visualization was deleted by the user from event analytics. Do we want the user to manually update the operational panel by deleting the visualization which have error or should we delete them at the same moment when the saved visualization is deleted from visualization list on event analytics?
> 
> Thanks, Ruchika

**Comment by ruchika-narang** [comment]
This is an existing functionality and no changes were to this. As discussed in the sync up call closing this one. Thanks!!
