### ISSUE TITLE
[FEATURE]: UI changes

### ISSUE THREAD

**Issue by pratibhapandey16** [opensearch-project/observability#966]
- Vertical scrolling should only be limited in each panel, no page scrolling
- Query bar and search section should always be visible
- Data configurations should have minimal width
- Data configurations did not yet fully follow UX design which should have fields drilldown

@anirudha @mengweieric
cc: @abasatwar @spattnaik

**Comment by mengweieric** [comment]
#1044 addressed this issue and already merged in.
