### ISSUE TITLE
[BUG]: 'X' button in Data Configurations panel for Logs view

### ISSUE THREAD

**Issue by pratibhapandey16** [opensearch-project/observability#976]
**What is the bug?**
Red cross button appears beside Field title in Data Configurations panel for Logs view when we have stats section in the PPL query.

**How can one reproduce the bug?**
1.Launch OpenSearch Dashboard UI
Go to Observability->Event Analytics->Explorer
2. Enter PPL Query and select "Year to date" option from calendar 
    Query "source = opensearch_dashboards_sample_data_logs | stats count(), max(bytes) by span(timestamp,1d), clientip, host"
3. Click Refresh
4. Click on Visualizations tab
5. Select the Logs view option from chart selector dropdown
6. Observe red cross 'X' button beside Field title which is disabled.

**What is the expected behavior?**
The cross button should not be visible as its disabled and of no use.

**Do you have any screenshots?**
![image](https://user-images.githubusercontent.com/103417380/187428117-5bbf7492-38bd-47b7-b434-1f33bfe7ee35.png)

@anirudha @mengweieric
cc: @abasatwar @spattnaik

**Comment by saisanju-s** [comment]
Hey @mengweieric , @anirudha - Let us know if we need to fix this issue?
