### ISSUE TITLE
[BUG]: Range Slider for Line width for Vertical Bar chart

### ISSUE THREAD

**Issue by pratibhapandey16** [opensearch-project/observability#981]
**What is the bug?**
Range Slider for Line width only allows range from 0 to 10 but if we manually enter a value greater than 10 it still updates the chart according to the entered value.

**How can one reproduce the bug?**
1. Launch OpenSearch Dashboard UI
Go to Observability->Event Analytics->Explorer
2. Enter PPL Query and select "Year to date" option from calendar
3. Click Refresh
4. Click on Visualizations tab
5. Select the Vertical bar chart option from chart selector dropdown
6. Try to enter a value greater than 10 for Line Width

**What is the expected behavior?**
The chart should not get updated if user enters any value apart from 0 to 10

@anirudha @mengweieric
cc: @abasatwar @spattnaik

**Comment by abhaypersistent** [comment]
Hi @mengweieric,

In all the chart styles we have added the tooltip. Please let me know if any changes are needed in the tooltip message.



<img width="663" alt="tooltip" src="https://user-images.githubusercontent.com/102669033/195130581-cab0a760-f7e6-4044-898e-57e074cdedcd.png">

Thanks
Abhay

@ruchika-narang @spattnaik

**Comment by ruchika-narang** [comment]
Merged to main
