### ISSUE TITLE
[BUG]: Resizable icon for Fields section on Visualizations page

### ISSUE THREAD

**Issue by pratibhapandey16** [opensearch-project/observability#989]
**What is the bug?**
The resizable icon for fields section gets changed along with Data Config panel resizable icon when we collapse Data Config panel.

**How can one reproduce the bug?**
1. Launch OpenSearch Dashboard UI
Go to Observability->Event Analytics->Explorer
2. Enter PPL Query and select "Year to date" option from calendar
3. Click Refresh
4. Click on Visualizations tab
5. Select the Vertical bar chart option from chart selector dropdown
6. Click on Data Config resizable icon 

**What is the expected behavior?**
The resizable icon for fields section should not change if the user clicks on Data Config panel resizable icon

**Do you have any screenshots?**
![image](https://user-images.githubusercontent.com/103417380/188553227-6e150b01-014f-4d1d-a7db-a5ce550f090c.png)

@anirudha @mengweieric
cc: @abasatwar @spattnaik

**Comment by ramneet-persistent** [comment]
Fields section and data config resize configuration is modified and collapse icon on fields section is not visible not.
